spring:
  application:
    name: scraper-website
  profiles:
    active: dev

server:
  port: 8091

website:
  scraper:
    timeout-ms: 15000
    max-items: 40
    respect-robots-txt: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
