-- Real European IT companies (replaces runtime demo seeder)
INSERT INTO companies (id, name, website, industry, city_id, country_code) VALUES
  ('co-zalando', 'Zalando', 'https://www.zalando.com', 'E-commerce', 'DE-berlin', 'DE'),
  ('co-deliveryhero', 'Delivery Hero', 'https://www.deliveryhero.com', 'FoodTech', 'DE-berlin', 'DE'),
  ('co-hellofresh', 'HelloFresh', 'https://www.hellofresh.com', 'FoodTech', 'DE-berlin', 'DE'),
  ('co-n26', 'N26', 'https://n26.com', 'FinTech', 'DE-berlin', 'DE'),
  ('co-soundcloud', 'SoundCloud', 'https://soundcloud.com', 'Media', 'DE-berlin', 'DE'),
  ('co-contentful', 'Contentful', 'https://www.contentful.com', 'SaaS', 'DE-berlin', 'DE'),
  ('co-omio', 'Omio', 'https://www.omio.com', 'Travel', 'DE-berlin', 'DE'),
  ('co-adjust', 'Adjust', 'https://www.adjust.com', 'AdTech', 'DE-berlin', 'DE'),
  ('co-auto1', 'AUTO1 Group', 'https://www.auto1-group.com', 'Automotive', 'DE-berlin', 'DE'),
  ('co-traderepublic', 'Trade Republic', 'https://traderepublic.com', 'FinTech', 'DE-berlin', 'DE'),
  ('co-celonis', 'Celonis', 'https://www.celonis.com', 'SaaS', 'DE-munich', 'DE'),
  ('co-personio', 'Personio', 'https://www.personio.com', 'HR Tech', 'DE-munich', 'DE'),
  ('co-siemens', 'Siemens', 'https://www.siemens.com', 'Industrial', 'DE-munich', 'DE'),
  ('co-freeletics', 'Freeletics', 'https://www.freeletics.com', 'HealthTech', 'DE-munich', 'DE'),
  ('co-check24', 'CHECK24', 'https://www.check24.de', 'Comparison', 'DE-munich', 'DE'),
  ('co-flixbus', 'Flix', 'https://www.flixbus.com', 'Mobility', 'DE-munich', 'DE'),
  ('co-jimdo', 'Jimdo', 'https://www.jimdo.com', 'SaaS', 'DE-hamburg', 'DE'),
  ('co-innogames', 'InnoGames', 'https://www.innogames.com', 'Gaming', 'DE-hamburg', 'DE'),
  ('co-statista', 'Statista', 'https://www.statista.com', 'Data', 'DE-hamburg', 'DE'),
  ('co-aboutyou', 'ABOUT YOU', 'https://www.aboutyou.com', 'E-commerce', 'DE-hamburg', 'DE'),
  ('co-newwork', 'New Work SE', 'https://www.new-work.se', 'HR Tech', 'DE-hamburg', 'DE'),
  ('co-adesso', 'Adesso SE', 'https://www.adesso.de', 'Consulting', 'DE-frankfurt', 'DE'),
  ('co-deutscheboerse', 'Deutsche Börse', 'https://www.deutsche-boerse.com', 'FinTech', 'DE-frankfurt', 'DE'),
  ('co-teamviewer', 'TeamViewer', 'https://www.teamviewer.com', 'SaaS', 'DE-stuttgart', 'DE'),
  ('co-sap', 'SAP', 'https://www.sap.com', 'Enterprise Software', 'DE-stuttgart', 'DE'),
  ('co-bosch', 'Bosch', 'https://www.bosch.com', 'Industrial', 'DE-stuttgart', 'DE'),
  ('co-trivago', 'trivago', 'https://www.trivago.com', 'Travel', 'DE-düsseldorf', 'DE'),
  ('co-rewe-digital', 'REWE digital', 'https://www.rewe-digital.com', 'Retail Tech', 'DE-cologne', 'DE'),
  ('co-adyen', 'Adyen', 'https://www.adyen.com', 'Payments', 'NL-amsterdam', 'NL'),
  ('co-booking', 'Booking.com', 'https://www.booking.com', 'Travel', 'NL-amsterdam', 'NL'),
  ('co-mollie', 'Mollie', 'https://www.mollie.com', 'Payments', 'NL-amsterdam', 'NL'),
  ('co-tomtom', 'TomTom', 'https://www.tomtom.com', 'Navigation', 'NL-amsterdam', 'NL'),
  ('co-backbase', 'Backbase', 'https://www.backbase.com', 'FinTech', 'NL-amsterdam', 'NL'),
  ('co-bird', 'Bird', 'https://bird.com', 'Communications', 'NL-amsterdam', 'NL'),
  ('co-picnic', 'Picnic', 'https://www.picnic.app', 'Retail', 'NL-amsterdam', 'NL'),
  ('co-coolblue', 'Coolblue', 'https://www.coolblue.nl', 'E-commerce', 'NL-rotterdam', 'NL'),
  ('co-rabobank', 'Rabobank', 'https://www.rabobank.com', 'Banking', 'NL-utrecht', 'NL'),
  ('co-asml', 'ASML', 'https://www.asml.com', 'Semiconductor', 'NL-eindhoven', 'NL'),
  ('co-philips', 'Philips', 'https://www.philips.com', 'HealthTech', 'NL-eindhoven', 'NL'),
  ('co-kpn', 'KPN', 'https://www.kpn.com', 'Telecom', 'NL-the-hague', 'NL'),
  ('co-imec', 'imec', 'https://www.imec-int.com', 'R&D', 'BE-leuven', 'BE'),
  ('co-odoo', 'Odoo', 'https://www.odoo.com', 'ERP', 'BE-brussels', 'BE'),
  ('co-collibra', 'Collibra', 'https://www.collibra.com', 'Data', 'BE-brussels', 'BE'),
  ('co-cegeka', 'Cegeka', 'https://www.cegeka.com', 'Consulting', 'BE-antwerp', 'BE'),
  ('co-materialise', 'Materialise', 'https://www.materialise.com', '3D Printing', 'BE-leuven', 'BE'),
  ('co-capgemini', 'Capgemini', 'https://www.capgemini.com', 'Consulting', 'FR-paris', 'FR'),
  ('co-dassault', 'Dassault Systèmes', 'https://www.3ds.com', 'Software', 'FR-paris', 'FR'),
  ('co-criteo', 'Criteo', 'https://www.criteo.com', 'AdTech', 'FR-paris', 'FR'),
  ('co-blablacar', 'BlaBlaCar', 'https://www.blablacar.com', 'Mobility', 'FR-paris', 'FR'),
  ('co-ledger', 'Ledger', 'https://www.ledger.com', 'Crypto', 'FR-paris', 'FR'),
  ('co-atos', 'Atos', 'https://atos.net', 'Consulting', 'FR-paris', 'FR'),
  ('co-ovhcloud', 'OVHcloud', 'https://www.ovhcloud.com', 'Cloud', 'FR-lille', 'FR'),
  ('co-sopra', 'Sopra Steria', 'https://www.soprasteria.com', 'Consulting', 'FR-lyon', 'FR'),
  ('co-worldline', 'Worldline', 'https://worldline.com', 'Payments', 'FR-marseille', 'FR'),
  ('co-airbus', 'Airbus', 'https://www.airbus.com', 'Aerospace', 'FR-toulouse', 'FR'),
  ('co-telefonica', 'Telefónica', 'https://www.telefonica.com', 'Telecom', 'ES-madrid', 'ES'),
  ('co-cabify', 'Cabify', 'https://cabify.com', 'Mobility', 'ES-madrid', 'ES'),
  ('co-jobandtalent', 'Jobandtalent', 'https://jobandtalent.com', 'HR Tech', 'ES-madrid', 'ES'),
  ('co-glovo', 'Glovo', 'https://glovoapp.com', 'Delivery', 'ES-barcelona', 'ES'),
  ('co-typeform', 'Typeform', 'https://www.typeform.com', 'SaaS', 'ES-barcelona', 'ES'),
  ('co-wallapop', 'Wallapop', 'https://www.wallapop.com', 'Marketplace', 'ES-barcelona', 'ES'),
  ('co-indra', 'Indra', 'https://www.indracompany.com', 'Consulting', 'ES-madrid', 'ES'),
  ('co-bbva', 'BBVA', 'https://www.bbva.com', 'Banking', 'ES-bilbao', 'ES'),
  ('co-reply', 'Reply', 'https://www.reply.com', 'Consulting', 'IT-turin', 'IT'),
  ('co-bendingspoons', 'Bending Spoons', 'https://bendingspoons.com', 'Apps', 'IT-milan', 'IT'),
  ('co-teamsystem', 'TeamSystem', 'https://www.teamsystem.com', 'ERP', 'IT-milan', 'IT'),
  ('co-eng', 'Engineering', 'https://www.eng.it', 'Consulting', 'IT-rome', 'IT'),
  ('co-sorint', 'SORINT.lab', 'https://www.sorint.it', 'Consulting', 'IT-bologna', 'IT'),
  ('co-farfetch', 'Farfetch', 'https://www.farfetch.com', 'E-commerce', 'PT-porto', 'PT'),
  ('co-talkdesk', 'Talkdesk', 'https://www.talkdesk.com', 'SaaS', 'PT-lisbon', 'PT'),
  ('co-outsystems', 'OutSystems', 'https://www.outsystems.com', 'Low-code', 'PT-lisbon', 'PT'),
  ('co-feedzai', 'Feedzai', 'https://feedzai.com', 'FinTech', 'PT-coimbra', 'PT'),
  ('co-critical', 'Critical Software', 'https://www.criticalsoftware.com', 'Software', 'PT-coimbra', 'PT'),
  ('co-blip', 'Blip', 'https://blip.pt', 'Consulting', 'PT-braga', 'PT'),
  ('co-opera', 'Opera', 'https://www.opera.com', 'Browser', 'NO-oslo', 'NO'),
  ('co-kahoot', 'Kahoot!', 'https://kahoot.com', 'EdTech', 'NO-oslo', 'NO'),
  ('co-cognite', 'Cognite', 'https://www.cognite.com', 'Industrial AI', 'NO-oslo', 'NO'),
  ('co-visma', 'Visma', 'https://www.visma.com', 'SaaS', 'NO-oslo', 'NO'),
  ('co-tietoevry', 'Tietoevry', 'https://www.tietoevry.com', 'Consulting', 'NO-bergen', 'NO'),
  ('co-spotify', 'Spotify', 'https://www.spotify.com', 'Media', 'SE-stockholm', 'SE'),
  ('co-klarna', 'Klarna', 'https://www.klarna.com', 'FinTech', 'SE-stockholm', 'SE'),
  ('co-ericsson', 'Ericsson', 'https://www.ericsson.com', 'Telecom', 'SE-stockholm', 'SE'),
  ('co-truecaller', 'Truecaller', 'https://www.truecaller.com', 'Communications', 'SE-stockholm', 'SE'),
  ('co-volvo', 'Volvo Cars', 'https://www.volvocars.com', 'Automotive', 'SE-gothenburg', 'SE'),
  ('co-mentimeter', 'Mentimeter', 'https://www.mentimeter.com', 'SaaS', 'SE-stockholm', 'SE'),
  ('co-maersk', 'Maersk', 'https://www.maersk.com', 'Logistics', 'DK-copenhagen', 'DK'),
  ('co-unity', 'Unity Technologies', 'https://unity.com', 'Gaming', 'DK-copenhagen', 'DK'),
  ('co-trustpilot', 'Trustpilot', 'https://www.trustpilot.com', 'SaaS', 'DK-copenhagen', 'DK'),
  ('co-vestas', 'Vestas', 'https://www.vestas.com', 'Energy', 'DK-aarhus', 'DK'),
  ('co-nokia', 'Nokia', 'https://www.nokia.com', 'Telecom', 'FI-espoo', 'FI'),
  ('co-supercell', 'Supercell', 'https://supercell.com', 'Gaming', 'FI-helsinki', 'FI'),
  ('co-wolt', 'Wolt', 'https://wolt.com', 'Delivery', 'FI-helsinki', 'FI'),
  ('co-relex', 'RELEX Solutions', 'https://www.relexsolutions.com', 'Retail Tech', 'FI-helsinki', 'FI'),
  ('co-qt', 'Qt Group', 'https://www.qt.io', 'Software', 'FI-oulu', 'FI'),
  ('co-stripe-ie', 'Stripe', 'https://stripe.com', 'Payments', 'IE-dublin', 'IE'),
  ('co-intercom', 'Intercom', 'https://www.intercom.com', 'SaaS', 'IE-dublin', 'IE'),
  ('co-workday-ie', 'Workday', 'https://www.workday.com', 'ERP', 'IE-dublin', 'IE'),
  ('co-version1', 'Version 1', 'https://www.version1.com', 'Consulting', 'IE-cork', 'IE'),
  ('co-soti', 'SOTI', 'https://www.soti.net', 'MDM', 'IE-galway', 'IE'),
  ('co-allegro', 'Allegro', 'https://allegro.pl', 'E-commerce', 'PL-poznań', 'PL'),
  ('co-asseco', 'Asseco Poland', 'https://asseco.com', 'Software', 'PL-kraków', 'PL'),
  ('co-cdprojekt', 'CD Projekt', 'https://www.cdprojekt.com', 'Gaming', 'PL-warsaw', 'PL'),
  ('co-comarch', 'Comarch', 'https://www.comarch.com', 'ERP', 'PL-kraków', 'PL'),
  ('co-netguru', 'Netguru', 'https://www.netguru.com', 'Consulting', 'PL-poznań', 'PL'),
  ('co-text', 'Text', 'https://text.com', 'SaaS', 'PL-wrocław', 'PL'),
  ('co-intive', 'intive', 'https://www.intive.com', 'Consulting', 'PL-gdańsk', 'PL'),
  ('co-bitpanda', 'Bitpanda', 'https://www.bitpanda.com', 'Crypto', 'AT-vienna', 'AT'),
  ('co-tricentis', 'Tricentis', 'https://www.tricentis.com', 'Testing', 'AT-vienna', 'AT'),
  ('co-raiffeisen', 'Raiffeisen Bank International', 'https://www.rbinternational.com', 'Banking', 'AT-vienna', 'AT'),
  ('co-ams', 'ams OSRAM', 'https://ams.com', 'Semiconductor', 'AT-graz', 'AT'),
  ('co-abb', 'ABB', 'https://global.abb', 'Industrial', 'CH-zurich', 'CH'),
  ('co-logitech', 'Logitech', 'https://www.logitech.com', 'Hardware', 'CH-lausanne', 'CH'),
  ('co-swisscom', 'Swisscom', 'https://www.swisscom.ch', 'Telecom', 'CH-bern', 'CH'),
  ('co-sonarsource', 'SonarSource', 'https://www.sonarsource.com', 'DevTools', 'CH-geneva', 'CH'),
  ('co-temenos', 'Temenos', 'https://www.temenos.com', 'FinTech', 'CH-geneva', 'CH'),
  ('co-roche', 'Roche', 'https://www.roche.com', 'Pharma', 'CH-basel', 'CH');

INSERT INTO company_categories (company_id, category_id) VALUES
  ('co-zalando', 'software-dev'),
  ('co-zalando', 'saas'),
  ('co-deliveryhero', 'mobile'),
  ('co-deliveryhero', 'saas'),
  ('co-hellofresh', 'saas'),
  ('co-hellofresh', 'data-eng'),
  ('co-n26', 'fintech'),
  ('co-n26', 'mobile'),
  ('co-soundcloud', 'software-dev'),
  ('co-soundcloud', 'mobile'),
  ('co-contentful', 'saas'),
  ('co-contentful', 'api'),
  ('co-omio', 'software-dev'),
  ('co-omio', 'mobile'),
  ('co-adjust', 'data-eng'),
  ('co-adjust', 'mobile'),
  ('co-auto1', 'software-dev'),
  ('co-auto1', 'saas'),
  ('co-traderepublic', 'fintech'),
  ('co-traderepublic', 'mobile'),
  ('co-celonis', 'saas'),
  ('co-celonis', 'data-eng'),
  ('co-celonis', 'ai'),
  ('co-personio', 'saas'),
  ('co-personio', 'cloud'),
  ('co-siemens', 'software-dev'),
  ('co-siemens', 'automation'),
  ('co-freeletics', 'mobile'),
  ('co-freeletics', 'healthtech'),
  ('co-check24', 'web-dev'),
  ('co-check24', 'saas'),
  ('co-flixbus', 'software-dev'),
  ('co-flixbus', 'mobile'),
  ('co-jimdo', 'saas'),
  ('co-jimdo', 'web-dev'),
  ('co-innogames', 'software-dev'),
  ('co-innogames', 'mobile'),
  ('co-statista', 'data-eng'),
  ('co-statista', 'saas'),
  ('co-aboutyou', 'software-dev'),
  ('co-aboutyou', 'saas'),
  ('co-newwork', 'saas'),
  ('co-newwork', 'recruitment'),
  ('co-adesso', 'consulting'),
  ('co-adesso', 'software-dev'),
  ('co-deutscheboerse', 'fintech'),
  ('co-deutscheboerse', 'data-eng'),
  ('co-teamviewer', 'saas'),
  ('co-teamviewer', 'cloud'),
  ('co-sap', 'erp'),
  ('co-sap', 'saas'),
  ('co-sap', 'cloud'),
  ('co-bosch', 'automation'),
  ('co-bosch', 'software-dev'),
  ('co-trivago', 'software-dev'),
  ('co-trivago', 'data-eng'),
  ('co-rewe-digital', 'software-dev'),
  ('co-rewe-digital', 'cloud'),
  ('co-adyen', 'fintech'),
  ('co-adyen', 'api'),
  ('co-booking', 'software-dev'),
  ('co-booking', 'cloud'),
  ('co-mollie', 'fintech'),
  ('co-mollie', 'api'),
  ('co-tomtom', 'software-dev'),
  ('co-tomtom', 'mobile'),
  ('co-backbase', 'fintech'),
  ('co-backbase', 'saas'),
  ('co-bird', 'api'),
  ('co-bird', 'saas'),
  ('co-picnic', 'software-dev'),
  ('co-picnic', 'data-eng'),
  ('co-coolblue', 'software-dev'),
  ('co-coolblue', 'cloud'),
  ('co-rabobank', 'fintech'),
  ('co-rabobank', 'cloud'),
  ('co-asml', 'software-dev'),
  ('co-asml', 'automation'),
  ('co-philips', 'healthtech'),
  ('co-philips', 'software-dev'),
  ('co-kpn', 'cloud'),
  ('co-kpn', 'devops'),
  ('co-imec', 'ai'),
  ('co-imec', 'software-dev'),
  ('co-odoo', 'erp'),
  ('co-odoo', 'saas'),
  ('co-collibra', 'data-eng'),
  ('co-collibra', 'saas'),
  ('co-cegeka', 'consulting'),
  ('co-cegeka', 'cloud'),
  ('co-materialise', 'software-dev'),
  ('co-materialise', 'healthtech'),
  ('co-capgemini', 'consulting'),
  ('co-capgemini', 'cloud'),
  ('co-dassault', 'software-dev'),
  ('co-dassault', 'saas'),
  ('co-criteo', 'data-eng'),
  ('co-criteo', 'ai'),
  ('co-blablacar', 'mobile'),
  ('co-blablacar', 'software-dev'),
  ('co-ledger', 'blockchain'),
  ('co-ledger', 'fintech'),
  ('co-atos', 'consulting'),
  ('co-atos', 'cloud'),
  ('co-ovhcloud', 'cloud'),
  ('co-ovhcloud', 'devops'),
  ('co-sopra', 'consulting'),
  ('co-sopra', 'digital-xform'),
  ('co-worldline', 'fintech'),
  ('co-worldline', 'api'),
  ('co-airbus', 'software-dev'),
  ('co-airbus', 'automation'),
  ('co-telefonica', 'cloud'),
  ('co-telefonica', 'software-dev'),
  ('co-cabify', 'mobile'),
  ('co-cabify', 'software-dev'),
  ('co-jobandtalent', 'recruitment'),
  ('co-jobandtalent', 'saas'),
  ('co-glovo', 'mobile'),
  ('co-glovo', 'software-dev'),
  ('co-typeform', 'saas'),
  ('co-typeform', 'api'),
  ('co-wallapop', 'mobile'),
  ('co-wallapop', 'software-dev'),
  ('co-indra', 'consulting'),
  ('co-indra', 'software-dev'),
  ('co-bbva', 'fintech'),
  ('co-bbva', 'cloud'),
  ('co-reply', 'consulting'),
  ('co-reply', 'ai'),
  ('co-bendingspoons', 'mobile'),
  ('co-bendingspoons', 'saas'),
  ('co-teamsystem', 'erp'),
  ('co-teamsystem', 'saas'),
  ('co-eng', 'consulting'),
  ('co-eng', 'software-dev'),
  ('co-sorint', 'devops'),
  ('co-sorint', 'cloud'),
  ('co-farfetch', 'software-dev'),
  ('co-farfetch', 'saas'),
  ('co-talkdesk', 'saas'),
  ('co-talkdesk', 'ai'),
  ('co-outsystems', 'saas'),
  ('co-outsystems', 'web-dev'),
  ('co-feedzai', 'ai'),
  ('co-feedzai', 'fintech'),
  ('co-critical', 'software-dev'),
  ('co-critical', 'cyber'),
  ('co-blip', 'consulting'),
  ('co-blip', 'cloud'),
  ('co-opera', 'software-dev'),
  ('co-opera', 'mobile'),
  ('co-kahoot', 'edtech'),
  ('co-kahoot', 'saas'),
  ('co-cognite', 'ai'),
  ('co-cognite', 'data-eng'),
  ('co-visma', 'saas'),
  ('co-visma', 'erp'),
  ('co-tietoevry', 'consulting'),
  ('co-tietoevry', 'cloud'),
  ('co-spotify', 'software-dev'),
  ('co-spotify', 'data-eng'),
  ('co-klarna', 'fintech'),
  ('co-klarna', 'api'),
  ('co-ericsson', 'software-dev'),
  ('co-ericsson', 'cloud'),
  ('co-truecaller', 'mobile'),
  ('co-truecaller', 'ai'),
  ('co-volvo', 'software-dev'),
  ('co-volvo', 'automation'),
  ('co-mentimeter', 'saas'),
  ('co-mentimeter', 'web-dev'),
  ('co-maersk', 'software-dev'),
  ('co-maersk', 'cloud'),
  ('co-unity', 'software-dev'),
  ('co-unity', 'mobile'),
  ('co-trustpilot', 'saas'),
  ('co-trustpilot', 'api'),
  ('co-vestas', 'software-dev'),
  ('co-vestas', 'data-eng'),
  ('co-nokia', 'software-dev'),
  ('co-nokia', 'cloud'),
  ('co-supercell', 'mobile'),
  ('co-supercell', 'software-dev'),
  ('co-wolt', 'mobile'),
  ('co-wolt', 'software-dev'),
  ('co-relex', 'ai'),
  ('co-relex', 'saas'),
  ('co-qt', 'software-dev'),
  ('co-qt', 'mobile'),
  ('co-stripe-ie', 'fintech'),
  ('co-stripe-ie', 'api'),
  ('co-intercom', 'saas'),
  ('co-intercom', 'api'),
  ('co-workday-ie', 'erp'),
  ('co-workday-ie', 'saas'),
  ('co-version1', 'consulting'),
  ('co-version1', 'cloud'),
  ('co-soti', 'mobile'),
  ('co-soti', 'saas'),
  ('co-allegro', 'software-dev'),
  ('co-allegro', 'cloud'),
  ('co-asseco', 'software-dev'),
  ('co-asseco', 'erp'),
  ('co-cdprojekt', 'software-dev'),
  ('co-cdprojekt', 'mobile'),
  ('co-comarch', 'erp'),
  ('co-comarch', 'saas'),
  ('co-netguru', 'web-dev'),
  ('co-netguru', 'consulting'),
  ('co-text', 'saas'),
  ('co-text', 'api'),
  ('co-intive', 'consulting'),
  ('co-intive', 'software-dev'),
  ('co-bitpanda', 'fintech'),
  ('co-bitpanda', 'blockchain'),
  ('co-tricentis', 'devops'),
  ('co-tricentis', 'saas'),
  ('co-raiffeisen', 'fintech'),
  ('co-raiffeisen', 'cloud'),
  ('co-ams', 'software-dev'),
  ('co-ams', 'automation'),
  ('co-abb', 'automation'),
  ('co-abb', 'software-dev'),
  ('co-logitech', 'software-dev'),
  ('co-logitech', 'mobile'),
  ('co-swisscom', 'cloud'),
  ('co-swisscom', 'devops'),
  ('co-sonarsource', 'devops'),
  ('co-sonarsource', 'saas'),
  ('co-temenos', 'fintech'),
  ('co-temenos', 'saas'),
  ('co-roche', 'healthtech'),
  ('co-roche', 'data-eng');
