INSERT INTO countries (code, name) VALUES
  ('DE', 'Germany'),
  ('NL', 'Netherlands'),
  ('BE', 'Belgium'),
  ('FR', 'France'),
  ('ES', 'Spain'),
  ('IT', 'Italy'),
  ('PT', 'Portugal'),
  ('NO', 'Norway'),
  ('SE', 'Sweden'),
  ('DK', 'Denmark'),
  ('FI', 'Finland'),
  ('IE', 'Ireland'),
  ('PL', 'Poland'),
  ('AT', 'Austria'),
  ('CH', 'Switzerland');

INSERT INTO cities (id, name, country_code) VALUES
  ('DE-berlin', 'Berlin', 'DE'),
  ('DE-munich', 'Munich', 'DE'),
  ('DE-hamburg', 'Hamburg', 'DE'),
  ('DE-frankfurt', 'Frankfurt', 'DE'),
  ('DE-cologne', 'Cologne', 'DE'),
  ('DE-stuttgart', 'Stuttgart', 'DE'),
  ('DE-düsseldorf', 'Düsseldorf', 'DE'),
  ('NL-amsterdam', 'Amsterdam', 'NL'),
  ('NL-rotterdam', 'Rotterdam', 'NL'),
  ('NL-the-hague', 'The Hague', 'NL'),
  ('NL-utrecht', 'Utrecht', 'NL'),
  ('NL-eindhoven', 'Eindhoven', 'NL'),
  ('BE-brussels', 'Brussels', 'BE'),
  ('BE-antwerp', 'Antwerp', 'BE'),
  ('BE-ghent', 'Ghent', 'BE'),
  ('BE-leuven', 'Leuven', 'BE'),
  ('FR-paris', 'Paris', 'FR'),
  ('FR-lyon', 'Lyon', 'FR'),
  ('FR-marseille', 'Marseille', 'FR'),
  ('FR-toulouse', 'Toulouse', 'FR'),
  ('FR-nantes', 'Nantes', 'FR'),
  ('FR-lille', 'Lille', 'FR'),
  ('ES-madrid', 'Madrid', 'ES'),
  ('ES-barcelona', 'Barcelona', 'ES'),
  ('ES-valencia', 'Valencia', 'ES'),
  ('ES-seville', 'Seville', 'ES'),
  ('ES-bilbao', 'Bilbao', 'ES'),
  ('IT-milan', 'Milan', 'IT'),
  ('IT-rome', 'Rome', 'IT'),
  ('IT-turin', 'Turin', 'IT'),
  ('IT-bologna', 'Bologna', 'IT'),
  ('IT-florence', 'Florence', 'IT'),
  ('PT-lisbon', 'Lisbon', 'PT'),
  ('PT-porto', 'Porto', 'PT'),
  ('PT-braga', 'Braga', 'PT'),
  ('PT-coimbra', 'Coimbra', 'PT'),
  ('NO-oslo', 'Oslo', 'NO'),
  ('NO-bergen', 'Bergen', 'NO'),
  ('NO-trondheim', 'Trondheim', 'NO'),
  ('SE-stockholm', 'Stockholm', 'SE'),
  ('SE-gothenburg', 'Gothenburg', 'SE'),
  ('SE-malmö', 'Malmö', 'SE'),
  ('SE-uppsala', 'Uppsala', 'SE'),
  ('DK-copenhagen', 'Copenhagen', 'DK'),
  ('DK-aarhus', 'Aarhus', 'DK'),
  ('DK-odense', 'Odense', 'DK'),
  ('FI-helsinki', 'Helsinki', 'FI'),
  ('FI-espoo', 'Espoo', 'FI'),
  ('FI-tampere', 'Tampere', 'FI'),
  ('FI-oulu', 'Oulu', 'FI'),
  ('IE-dublin', 'Dublin', 'IE'),
  ('IE-cork', 'Cork', 'IE'),
  ('IE-galway', 'Galway', 'IE'),
  ('IE-limerick', 'Limerick', 'IE'),
  ('PL-warsaw', 'Warsaw', 'PL'),
  ('PL-kraków', 'Kraków', 'PL'),
  ('PL-wrocław', 'Wrocław', 'PL'),
  ('PL-gdańsk', 'Gdańsk', 'PL'),
  ('PL-poznań', 'Poznań', 'PL'),
  ('AT-vienna', 'Vienna', 'AT'),
  ('AT-graz', 'Graz', 'AT'),
  ('AT-linz', 'Linz', 'AT'),
  ('AT-salzburg', 'Salzburg', 'AT'),
  ('CH-zurich', 'Zurich', 'CH'),
  ('CH-geneva', 'Geneva', 'CH'),
  ('CH-basel', 'Basel', 'CH'),
  ('CH-bern', 'Bern', 'CH'),
  ('CH-lausanne', 'Lausanne', 'CH');
