CREATE INDEX IF NOT EXISTS idx_cities_name ON cities (name);

INSERT INTO cities (id, name, country_code)
SELECT v.id, v.name, v.country_code
FROM (VALUES
  ('us-new-york', 'New York', 'US'),
  ('us-los-angeles', 'Los Angeles', 'US'),
  ('us-chicago', 'Chicago', 'US'),
  ('us-houston', 'Houston', 'US'),
  ('us-phoenix', 'Phoenix', 'US'),
  ('us-philadelphia', 'Philadelphia', 'US'),
  ('us-san-antonio', 'San Antonio', 'US'),
  ('us-san-diego', 'San Diego', 'US'),
  ('us-dallas', 'Dallas', 'US'),
  ('us-san-jose', 'San Jose', 'US'),
  ('us-austin', 'Austin', 'US'),
  ('us-seattle', 'Seattle', 'US'),
  ('us-boston', 'Boston', 'US'),
  ('us-miami', 'Miami', 'US'),
  ('us-atlanta', 'Atlanta', 'US'),
  ('us-denver', 'Denver', 'US'),
  ('us-washington-dc', 'Washington, D.C.', 'US'),
  ('ca-toronto', 'Toronto', 'CA'),
  ('ca-montreal', 'Montreal', 'CA'),
  ('ca-vancouver', 'Vancouver', 'CA'),
  ('ca-calgary', 'Calgary', 'CA'),
  ('ca-ottawa', 'Ottawa', 'CA'),
  ('mx-mexico-city', 'Mexico City', 'MX'),
  ('mx-guadalajara', 'Guadalajara', 'MX'),
  ('mx-monterrey', 'Monterrey', 'MX'),
  ('br-sao-paulo', 'Sao Paulo', 'BR'),
  ('br-rio-de-janeiro', 'Rio de Janeiro', 'BR'),
  ('br-brasilia', 'Brasilia', 'BR'),
  ('br-salvador', 'Salvador', 'BR'),
  ('ar-buenos-aires', 'Buenos Aires', 'AR'),
  ('cl-santiago', 'Santiago', 'CL'),
  ('co-bogota', 'Bogota', 'CO'),
  ('pe-lima', 'Lima', 'PE'),
  ('gb-london', 'London', 'GB'),
  ('gb-manchester', 'Manchester', 'GB'),
  ('gb-birmingham', 'Birmingham', 'GB'),
  ('gb-edinburgh', 'Edinburgh', 'GB'),
  ('gb-glasgow', 'Glasgow', 'GB'),
  ('fr-paris', 'Paris', 'FR'),
  ('de-berlin', 'Berlin', 'DE'),
  ('de-munich', 'Munich', 'DE'),
  ('de-hamburg', 'Hamburg', 'DE'),
  ('de-frankfurt', 'Frankfurt', 'DE'),
  ('it-rome', 'Rome', 'IT'),
  ('it-milan', 'Milan', 'IT'),
  ('es-madrid', 'Madrid', 'ES'),
  ('es-barcelona', 'Barcelona', 'ES'),
  ('nl-amsterdam', 'Amsterdam', 'NL'),
  ('nl-rotterdam', 'Rotterdam', 'NL'),
  ('be-brussels', 'Brussels', 'BE'),
  ('ch-zurich', 'Zurich', 'CH'),
  ('ch-geneva', 'Geneva', 'CH'),
  ('at-vienna', 'Vienna', 'AT'),
  ('se-stockholm', 'Stockholm', 'SE'),
  ('no-oslo', 'Oslo', 'NO'),
  ('dk-copenhagen', 'Copenhagen', 'DK'),
  ('fi-helsinki', 'Helsinki', 'FI'),
  ('ie-dublin', 'Dublin', 'IE'),
  ('pl-warsaw', 'Warsaw', 'PL'),
  ('pt-lisbon', 'Lisbon', 'PT'),
  ('gr-athens', 'Athens', 'GR'),
  ('cz-prague', 'Prague', 'CZ'),
  ('hu-budapest', 'Budapest', 'HU'),
  ('ro-bucharest', 'Bucharest', 'RO'),
  ('ua-kyiv', 'Kyiv', 'UA'),
  ('ru-moscow', 'Moscow', 'RU'),
  ('ru-saint-petersburg', 'Saint Petersburg', 'RU'),
  ('tr-istanbul', 'Istanbul', 'TR'),
  ('tr-ankara', 'Ankara', 'TR'),
  ('in-mumbai', 'Mumbai', 'IN'),
  ('in-delhi', 'Delhi', 'IN'),
  ('in-bengaluru', 'Bengaluru', 'IN'),
  ('in-hyderabad', 'Hyderabad', 'IN'),
  ('in-chennai', 'Chennai', 'IN'),
  ('in-kolkata', 'Kolkata', 'IN'),
  ('in-pune', 'Pune', 'IN'),
  ('in-ahmedabad', 'Ahmedabad', 'IN'),
  ('cn-beijing', 'Beijing', 'CN'),
  ('cn-shanghai', 'Shanghai', 'CN'),
  ('cn-guangzhou', 'Guangzhou', 'CN'),
  ('cn-shenzhen', 'Shenzhen', 'CN'),
  ('cn-chengdu', 'Chengdu', 'CN'),
  ('jp-tokyo', 'Tokyo', 'JP'),
  ('jp-osaka', 'Osaka', 'JP'),
  ('jp-yokohama', 'Yokohama', 'JP'),
  ('kr-seoul', 'Seoul', 'KR'),
  ('kr-busan', 'Busan', 'KR'),
  ('sg-singapore', 'Singapore', 'SG'),
  ('my-kuala-lumpur', 'Kuala Lumpur', 'MY'),
  ('th-bangkok', 'Bangkok', 'TH'),
  ('id-jakarta', 'Jakarta', 'ID'),
  ('ph-manila', 'Manila', 'PH'),
  ('vn-ho-chi-minh-city', 'Ho Chi Minh City', 'VN'),
  ('vn-hanoi', 'Hanoi', 'VN'),
  ('au-sydney', 'Sydney', 'AU'),
  ('au-melbourne', 'Melbourne', 'AU'),
  ('au-brisbane', 'Brisbane', 'AU'),
  ('au-perth', 'Perth', 'AU'),
  ('nz-auckland', 'Auckland', 'NZ'),
  ('za-johannesburg', 'Johannesburg', 'ZA'),
  ('za-cape-town', 'Cape Town', 'ZA'),
  ('eg-cairo', 'Cairo', 'EG'),
  ('ng-lagos', 'Lagos', 'NG'),
  ('ng-abuja', 'Abuja', 'NG'),
  ('ke-nairobi', 'Nairobi', 'KE'),
  ('ma-casablanca', 'Casablanca', 'MA'),
  ('ae-dubai', 'Dubai', 'AE'),
  ('ae-abu-dhabi', 'Abu Dhabi', 'AE'),
  ('sa-riyadh', 'Riyadh', 'SA'),
  ('sa-jeddah', 'Jeddah', 'SA'),
  ('il-tel-aviv', 'Tel Aviv', 'IL'),
  ('il-jerusalem', 'Jerusalem', 'IL'),
  ('qa-doha', 'Doha', 'QA'),
  ('kw-kuwait-city', 'Kuwait City', 'KW'),
  ('pk-karachi', 'Karachi', 'PK'),
  ('pk-lahore', 'Lahore', 'PK'),
  ('pk-islamabad', 'Islamabad', 'PK'),
  ('bd-dhaka', 'Dhaka', 'BD'),
  ('lk-colombo', 'Colombo', 'LK'),
  ('hk-hong-kong', 'Hong Kong', 'HK'),
  ('tw-taipei', 'Taipei', 'TW'),
  ('de-cologne', 'Cologne', 'DE'),
  ('es-valencia', 'Valencia', 'ES'),
  ('it-naples', 'Naples', 'IT'),
  ('ca-edmonton', 'Edmonton', 'CA'),
  ('us-san-francisco', 'San Francisco', 'US')
) AS v(id, name, country_code)
WHERE NOT EXISTS (SELECT 1 FROM cities c WHERE c.id = v.id);
