-- Expand city coverage so selecting a country lists its major cities.

INSERT INTO cities (id, name, country_code)
SELECT v.id, v.name, v.country_code
FROM (VALUES
  -- Pakistan
  ('pk-faisalabad', 'Faisalabad', 'PK'),
  ('pk-rawalpindi', 'Rawalpindi', 'PK'),
  ('pk-multan', 'Multan', 'PK'),
  ('pk-peshawar', 'Peshawar', 'PK'),
  ('pk-quetta', 'Quetta', 'PK'),
  ('pk-sialkot', 'Sialkot', 'PK'),
  ('pk-gujranwala', 'Gujranwala', 'PK'),
  ('pk-hyderabad', 'Hyderabad', 'PK'),
  ('pk-sukkur', 'Sukkur', 'PK'),
  ('pk-bahawalpur', 'Bahawalpur', 'PK'),
  ('pk-sargodha', 'Sargodha', 'PK'),
  ('pk-sheikhupura', 'Sheikhupura', 'PK'),
  ('pk-rahim-yar-khan', 'Rahim Yar Khan', 'PK'),
  ('pk-jhang', 'Jhang', 'PK'),
  ('pk-gujrat', 'Gujrat', 'PK'),
  ('pk-mardan', 'Mardan', 'PK'),
  ('pk-kasur', 'Kasur', 'PK'),
  ('pk-mingora', 'Mingora', 'PK'),
  ('pk-dera-ghazi-khan', 'Dera Ghazi Khan', 'PK'),
  ('pk-nawabshah', 'Nawabshah', 'PK'),
  ('pk-sahiwal', 'Sahiwal', 'PK'),
  ('pk-okara', 'Okara', 'PK'),
  ('pk-mirpur-khas', 'Mirpur Khas', 'PK'),
  ('pk-chiniot', 'Chiniot', 'PK'),
  ('pk-kamoke', 'Kamoke', 'PK'),
  ('pk-sadiqabad', 'Sadiqabad', 'PK'),
  ('pk-burewala', 'Burewala', 'PK'),
  ('pk-jacobabad', 'Jacobabad', 'PK'),
  ('pk-muzaffargarh', 'Muzaffargarh', 'PK'),
  ('pk-khanewal', 'Khanewal', 'PK'),
  ('pk-gojra', 'Gojra', 'PK'),
  ('pk-bahawalnagar', 'Bahawalnagar', 'PK'),
  ('pk-abbottabad', 'Abbottabad', 'PK'),
  ('pk-muridke', 'Muridke', 'PK'),
  ('pk-pakpattan', 'Pakpattan', 'PK'),
  ('pk-jhelum', 'Jhelum', 'PK'),
  ('pk-chaman', 'Chaman', 'PK'),
  ('pk-khanpur', 'Khanpur', 'PK'),
  ('pk-hafizabad', 'Hafizabad', 'PK'),
  ('pk-kohat', 'Kohat', 'PK'),
  ('pk-larkana', 'Larkana', 'PK'),
  ('pk-turbat', 'Turbat', 'PK'),
  ('pk-dera-ismail-khan', 'Dera Ismail Khan', 'PK'),
  ('pk-muzaffarabad', 'Muzaffarabad', 'PK'),
  ('pk-mirpur', 'Mirpur', 'PK'),
  ('pk-gwadar', 'Gwadar', 'PK'),
  ('pk-gilgit', 'Gilgit', 'PK'),
  ('pk-skardu', 'Skardu', 'PK'),
  ('pk-attock', 'Attock', 'PK'),
  ('pk-taxila', 'Taxila', 'PK'),
  ('pk-wah-cantonment', 'Wah Cantonment', 'PK'),
  ('pk-swabi', 'Swabi', 'PK'),
  ('pk-charsadda', 'Charsadda', 'PK'),
  ('pk-nowshera', 'Nowshera', 'PK'),
  ('pk-mansehra', 'Mansehra', 'PK'),
  ('pk-haripur', 'Haripur', 'PK'),
  ('pk-vehari', 'Vehari', 'PK'),
  ('pk-lodhran', 'Lodhran', 'PK'),
  ('pk-tando-adam', 'Tando Adam', 'PK'),
  ('pk-thatta', 'Thatta', 'PK'),

  -- India (extra metros / tech hubs)
  ('in-pune', 'Pune', 'IN'),
  ('in-ahmedabad', 'Ahmedabad', 'IN'),
  ('in-jaipur', 'Jaipur', 'IN'),
  ('in-lucknow', 'Lucknow', 'IN'),
  ('in-kanpur', 'Kanpur', 'IN'),
  ('in-nagpur', 'Nagpur', 'IN'),
  ('in-indore', 'Indore', 'IN'),
  ('in-thane', 'Thane', 'IN'),
  ('in-bhopal', 'Bhopal', 'IN'),
  ('in-visakhapatnam', 'Visakhapatnam', 'IN'),
  ('in-patna', 'Patna', 'IN'),
  ('in-vadodara', 'Vadodara', 'IN'),
  ('in-ghaziabad', 'Ghaziabad', 'IN'),
  ('in-ludhiana', 'Ludhiana', 'IN'),
  ('in-agra', 'Agra', 'IN'),
  ('in-nashik', 'Nashik', 'IN'),
  ('in-faridabad', 'Faridabad', 'IN'),
  ('in-meerut', 'Meerut', 'IN'),
  ('in-rajkot', 'Rajkot', 'IN'),
  ('in-varanasi', 'Varanasi', 'IN'),
  ('in-srinagar', 'Srinagar', 'IN'),
  ('in-amritsar', 'Amritsar', 'IN'),
  ('in-chandigarh', 'Chandigarh', 'IN'),
  ('in-coimbatore', 'Coimbatore', 'IN'),
  ('in-kochi', 'Kochi', 'IN'),
  ('in-mysore', 'Mysore', 'IN'),
  ('in-noida', 'Noida', 'IN'),
  ('in-gurgaon', 'Gurgaon', 'IN'),

  -- United Kingdom
  ('gb-birmingham', 'Birmingham', 'GB'),
  ('gb-leeds', 'Leeds', 'GB'),
  ('gb-glasgow', 'Glasgow', 'GB'),
  ('gb-sheffield', 'Sheffield', 'GB'),
  ('gb-liverpool', 'Liverpool', 'GB'),
  ('gb-bristol', 'Bristol', 'GB'),
  ('gb-newcastle', 'Newcastle', 'GB'),
  ('gb-nottingham', 'Nottingham', 'GB'),
  ('gb-leicester', 'Leicester', 'GB'),
  ('gb-edinburgh', 'Edinburgh', 'GB'),
  ('gb-cardiff', 'Cardiff', 'GB'),
  ('gb-belfast', 'Belfast', 'GB'),
  ('gb-cambridge', 'Cambridge', 'GB'),
  ('gb-oxford', 'Oxford', 'GB'),
  ('gb-reading', 'Reading', 'GB'),

  -- UAE
  ('ae-sharjah', 'Sharjah', 'AE'),
  ('ae-ajman', 'Ajman', 'AE'),
  ('ae-ras-al-khaimah', 'Ras Al Khaimah', 'AE'),
  ('ae-fujairah', 'Fujairah', 'AE'),
  ('ae-al-ain', 'Al Ain', 'AE'),

  -- Bangladesh
  ('bd-chittagong', 'Chittagong', 'BD'),
  ('bd-khulna', 'Khulna', 'BD'),
  ('bd-rajshahi', 'Rajshahi', 'BD'),
  ('bd-sylhet', 'Sylhet', 'BD'),

  -- Saudi Arabia
  ('sa-dammam', 'Dammam', 'SA'),
  ('sa-mecca', 'Mecca', 'SA'),
  ('sa-medina', 'Medina', 'SA'),
  ('sa-khobar', 'Khobar', 'SA'),

  -- United States (extra hubs)
  ('us-minneapolis', 'Minneapolis', 'US'),
  ('us-detroit', 'Detroit', 'US'),
  ('us-portland', 'Portland', 'US'),
  ('us-las-vegas', 'Las Vegas', 'US'),
  ('us-orlando', 'Orlando', 'US'),
  ('us-tampa', 'Tampa', 'US'),
  ('us-charlotte', 'Charlotte', 'US'),
  ('us-raleigh', 'Raleigh', 'US'),
  ('us-nashville', 'Nashville', 'US'),
  ('us-salt-lake-city', 'Salt Lake City', 'US'),
  ('us-pittsburgh', 'Pittsburgh', 'US'),
  ('us-columbus', 'Columbus', 'US'),
  ('us-indianapolis', 'Indianapolis', 'US'),
  ('us-kansas-city', 'Kansas City', 'US'),
  ('us-sacramento', 'Sacramento', 'US'),

  -- Canada
  ('ca-winnipeg', 'Winnipeg', 'CA'),
  ('ca-quebec-city', 'Quebec City', 'CA'),
  ('ca-hamilton', 'Hamilton', 'CA'),
  ('ca-kitchener', 'Kitchener', 'CA'),
  ('ca-victoria', 'Victoria', 'CA'),
  ('ca-halifax', 'Halifax', 'CA'),

  -- Australia
  ('au-adelaide', 'Adelaide', 'AU'),
  ('au-canberra', 'Canberra', 'AU'),
  ('au-hobart', 'Hobart', 'AU'),
  ('au-gold-coast', 'Gold Coast', 'AU'),

  -- Germany
  ('de-stuttgart', 'Stuttgart', 'DE'),
  ('de-dusseldorf', 'Düsseldorf', 'DE'),
  ('de-dortmund', 'Dortmund', 'DE'),
  ('de-essen', 'Essen', 'DE'),
  ('de-leipzig', 'Leipzig', 'DE'),
  ('de-bremen', 'Bremen', 'DE'),
  ('de-dresden', 'Dresden', 'DE'),
  ('de-hannover', 'Hannover', 'DE'),
  ('de-nuremberg', 'Nuremberg', 'DE')
) AS v(id, name, country_code)
WHERE NOT EXISTS (SELECT 1 FROM cities c WHERE c.id = v.id);
