-- Expand Netherlands city coverage for nationwide and city-level scrapes.

INSERT INTO cities (id, name, country_code)
SELECT v.id, v.name, v.country_code
FROM (VALUES
  ('nl-amsterdam', 'Amsterdam', 'NL'),
  ('nl-rotterdam', 'Rotterdam', 'NL'),
  ('nl-the-hague', 'The Hague', 'NL'),
  ('nl-utrecht', 'Utrecht', 'NL'),
  ('nl-eindhoven', 'Eindhoven', 'NL'),
  ('nl-groningen', 'Groningen', 'NL'),
  ('nl-tilburg', 'Tilburg', 'NL'),
  ('nl-almere', 'Almere', 'NL'),
  ('nl-breda', 'Breda', 'NL'),
  ('nl-nijmegen', 'Nijmegen', 'NL'),
  ('nl-apeldoorn', 'Apeldoorn', 'NL'),
  ('nl-haarlem', 'Haarlem', 'NL'),
  ('nl-arnhem', 'Arnhem', 'NL'),
  ('nl-zaanstad', 'Zaanstad', 'NL'),
  ('nl-amstelveen', 'Amstelveen', 'NL'),
  ('nl-haarlemmermeer', 'Haarlemmermeer', 'NL'),
  ('nl-s-hertogenbosch', 'Den Bosch / ''s-Hertogenbosch', 'NL'),
  ('nl-zwolle', 'Zwolle', 'NL'),
  ('nl-zoetermeer', 'Zoetermeer', 'NL'),
  ('nl-leiden', 'Leiden', 'NL'),
  ('nl-maastricht', 'Maastricht', 'NL'),
  ('nl-dordrecht', 'Dordrecht', 'NL'),
  ('nl-ede', 'Ede', 'NL'),
  ('nl-leeuwarden', 'Leeuwarden', 'NL'),
  ('nl-emmen', 'Emmen', 'NL'),
  ('nl-westland', 'Westland', 'NL'),
  ('nl-venlo', 'Venlo', 'NL'),
  ('nl-delft', 'Delft', 'NL'),
  ('nl-deventer', 'Deventer', 'NL'),
  ('nl-sittard-geleen', 'Sittard-Geleen', 'NL'),
  ('nl-helmond', 'Helmond', 'NL'),
  ('nl-hilversum', 'Hilversum', 'NL'),
  ('nl-hengelo', 'Hengelo', 'NL'),
  ('nl-amersfoort', 'Amersfoort', 'NL'),
  ('nl-alkmaar', 'Alkmaar', 'NL'),
  ('nl-enschede', 'Enschede', 'NL'),
  ('nl-heerlen', 'Heerlen', 'NL'),
  ('nl-zaandam', 'Zaandam', 'NL'),
  ('nl-schiedam', 'Schiedam', 'NL'),
  ('nl-spijkenisse', 'Spijkenisse', 'NL'),
  ('nl-purmerend', 'Purmerend', 'NL'),
  ('nl-roosendaal', 'Roosendaal', 'NL'),
  ('nl-oss', 'Oss', 'NL'),
  ('nl-gouda', 'Gouda', 'NL'),
  ('nl-middelburg', 'Middelburg', 'NL'),
  ('nl-vlissingen', 'Vlissingen', 'NL'),
  ('nl-assen', 'Assen', 'NL'),
  ('nl-lelystad', 'Lelystad', 'NL'),
  ('nl-hoorn', 'Hoorn', 'NL'),
  ('nl-veenendaal', 'Veenendaal', 'NL'),
  ('nl-nieuwegein', 'Nieuwegein', 'NL'),
  ('nl-capelle-aan-den-ijssel', 'Capelle aan den IJssel', 'NL'),
  ('nl-rijswijk', 'Rijswijk', 'NL'),
  ('nl-katwijk', 'Katwijk', 'NL'),
  ('nl-bergen-op-zoom', 'Bergen op Zoom', 'NL'),
  ('nl-barendrecht', 'Barendrecht', 'NL'),
  ('nl-hardenberg', 'Hardenberg', 'NL')
) AS v(id, name, country_code)
WHERE NOT EXISTS (SELECT 1 FROM cities c WHERE c.id = v.id);
