-- Expand major-city coverage so every seeded country lists and scrapes its key cities.

INSERT INTO cities (id, name, country_code)
SELECT v.id, v.name, v.country_code
FROM (VALUES
  -- Germany
  ('de-cologne', 'Cologne', 'DE'),
  ('de-dusseldorf', 'Düsseldorf', 'DE'),
  ('de-mannheim', 'Mannheim', 'DE'),
  ('de-karlsruhe', 'Karlsruhe', 'DE'),
  ('de-wiesbaden', 'Wiesbaden', 'DE'),
  ('de-munster', 'Münster', 'DE'),
  ('de-augsburg', 'Augsburg', 'DE'),
  ('de-freiburg', 'Freiburg', 'DE'),
  ('de-kiel', 'Kiel', 'DE'),
  ('de-erfurt', 'Erfurt', 'DE'),
  ('de-rostock', 'Rostock', 'DE'),
  ('de-mainz', 'Mainz', 'DE'),
  ('de-kassel', 'Kassel', 'DE'),
  ('de-hagen', 'Hagen', 'DE'),
  ('de-hamm', 'Hamm', 'DE'),
  ('de-saarbrucken', 'Saarbrücken', 'DE'),
  ('de-potsdam', 'Potsdam', 'DE'),
  ('de-ludwigshafen', 'Ludwigshafen', 'DE'),
  ('de-oldenburg', 'Oldenburg', 'DE'),
  ('de-osnabruck', 'Osnabrück', 'DE'),
  ('de-heidelberg', 'Heidelberg', 'DE'),
  ('de-paderborn', 'Paderborn', 'DE'),
  ('de-regensburg', 'Regensburg', 'DE'),
  ('de-wurzburg', 'Würzburg', 'DE'),
  ('de-ingolstadt', 'Ingolstadt', 'DE'),
  ('de-ulm', 'Ulm', 'DE'),
  ('de-heilbronn', 'Heilbronn', 'DE'),
  ('de-wolfsburg', 'Wolfsburg', 'DE'),
  ('de-gottingen', 'Göttingen', 'DE'),
  ('de-reutlingen', 'Reutlingen', 'DE'),
  ('de-koblenz', 'Koblenz', 'DE'),
  ('de-siegen', 'Siegen', 'DE'),
  ('de-hildesheim', 'Hildesheim', 'DE'),
  ('de-salzgitter', 'Salzgitter', 'DE'),
  ('de-cottbus', 'Cottbus', 'DE'),

  -- France
  ('fr-bordeaux', 'Bordeaux', 'FR'),
  ('fr-nice', 'Nice', 'FR'),
  ('fr-strasbourg', 'Strasbourg', 'FR'),
  ('fr-montpellier', 'Montpellier', 'FR'),
  ('fr-rennes', 'Rennes', 'FR'),
  ('fr-reims', 'Reims', 'FR'),
  ('fr-saint-etienne', 'Saint-Étienne', 'FR'),
  ('fr-toulon', 'Toulon', 'FR'),
  ('fr-le-havre', 'Le Havre', 'FR'),
  ('fr-grenoble', 'Grenoble', 'FR'),
  ('fr-dijon', 'Dijon', 'FR'),
  ('fr-angers', 'Angers', 'FR'),
  ('fr-nimes', 'Nîmes', 'FR'),
  ('fr-villeurbanne', 'Villeurbanne', 'FR'),
  ('fr-clermont-ferrand', 'Clermont-Ferrand', 'FR'),
  ('fr-le-mans', 'Le Mans', 'FR'),
  ('fr-aix-en-provence', 'Aix-en-Provence', 'FR'),
  ('fr-brest', 'Brest', 'FR'),
  ('fr-tours', 'Tours', 'FR'),
  ('fr-amiens', 'Amiens', 'FR'),
  ('fr-limoges', 'Limoges', 'FR'),
  ('fr-perpignan', 'Perpignan', 'FR'),
  ('fr-metz', 'Metz', 'FR'),
  ('fr-besancon', 'Besançon', 'FR'),
  ('fr-orleans', 'Orléans', 'FR'),
  ('fr-rouen', 'Rouen', 'FR'),
  ('fr-mulhouse', 'Mulhouse', 'FR'),
  ('fr-caen', 'Caen', 'FR'),
  ('fr-nancy', 'Nancy', 'FR'),
  ('fr-argenteuil', 'Argenteuil', 'FR'),
  ('fr-saint-denis', 'Saint-Denis', 'FR'),
  ('fr-roubaix', 'Roubaix', 'FR'),
  ('fr-tourcoing', 'Tourcoing', 'FR'),
  ('fr-nanterre', 'Nanterre', 'FR'),
  ('fr-avignon', 'Avignon', 'FR'),
  ('fr-poitiers', 'Poitiers', 'FR'),
  ('fr-versailles', 'Versailles', 'FR'),

  -- Spain
  ('es-malaga', 'Málaga', 'ES'),
  ('es-zaragoza', 'Zaragoza', 'ES'),
  ('es-murcia', 'Murcia', 'ES'),
  ('es-palma', 'Palma', 'ES'),
  ('es-las-palmas', 'Las Palmas', 'ES'),
  ('es-alicante', 'Alicante', 'ES'),
  ('es-cordoba', 'Córdoba', 'ES'),
  ('es-valladolid', 'Valladolid', 'ES'),
  ('es-vigo', 'Vigo', 'ES'),
  ('es-gijon', 'Gijón', 'ES'),
  ('es-hospitalet', 'L''Hospitalet', 'ES'),
  ('es-coruna', 'A Coruña', 'ES'),
  ('es-granada', 'Granada', 'ES'),
  ('es-vitoria', 'Vitoria-Gasteiz', 'ES'),
  ('es-elche', 'Elche', 'ES'),
  ('es-oviedo', 'Oviedo', 'ES'),
  ('es-badalona', 'Badalona', 'ES'),
  ('es-cartagena', 'Cartagena', 'ES'),
  ('es-terrassa', 'Terrassa', 'ES'),
  ('es-jerez', 'Jerez de la Frontera', 'ES'),
  ('es-sabadell', 'Sabadell', 'ES'),
  ('es-mostoles', 'Móstoles', 'ES'),
  ('es-alcala', 'Alcalá de Henares', 'ES'),
  ('es-pamplona', 'Pamplona', 'ES'),
  ('es-fuenlabrada', 'Fuenlabrada', 'ES'),
  ('es-almeria', 'Almería', 'ES'),
  ('es-leganes', 'Leganés', 'ES'),
  ('es-santander', 'Santander', 'ES'),
  ('es-burgos', 'Burgos', 'ES'),
  ('es-castellon', 'Castellón', 'ES'),
  ('es-albacete', 'Albacete', 'ES'),
  ('es-getafe', 'Getafe', 'ES'),
  ('es-salamanca', 'Salamanca', 'ES'),
  ('es-huelva', 'Huelva', 'ES'),
  ('es-logrono', 'Logroño', 'ES'),
  ('es-badajoz', 'Badajoz', 'ES'),
  ('es-san-sebastian', 'San Sebastián', 'ES'),
  ('es-leon', 'León', 'ES'),
  ('es-cadiz', 'Cádiz', 'ES'),
  ('es-tarragona', 'Tarragona', 'ES'),

  -- Italy
  ('it-naples', 'Naples', 'IT'),
  ('it-palermo', 'Palermo', 'IT'),
  ('it-genoa', 'Genoa', 'IT'),
  ('it-bologna', 'Bologna', 'IT'),
  ('it-florence', 'Florence', 'IT'),
  ('it-bari', 'Bari', 'IT'),
  ('it-catania', 'Catania', 'IT'),
  ('it-venice', 'Venice', 'IT'),
  ('it-verona', 'Verona', 'IT'),
  ('it-messina', 'Messina', 'IT'),
  ('it-padua', 'Padua', 'IT'),
  ('it-trieste', 'Trieste', 'IT'),
  ('it-taranto', 'Taranto', 'IT'),
  ('it-brescia', 'Brescia', 'IT'),
  ('it-parma', 'Parma', 'IT'),
  ('it-modena', 'Modena', 'IT'),
  ('it-reggio-calabria', 'Reggio Calabria', 'IT'),
  ('it-reggio-emilia', 'Reggio Emilia', 'IT'),
  ('it-perugia', 'Perugia', 'IT'),
  ('it-livorno', 'Livorno', 'IT'),
  ('it-ravenna', 'Ravenna', 'IT'),
  ('it-cagliari', 'Cagliari', 'IT'),
  ('it-foggia', 'Foggia', 'IT'),
  ('it-rimini', 'Rimini', 'IT'),
  ('it-salerno', 'Salerno', 'IT'),
  ('it-ferrara', 'Ferrara', 'IT'),
  ('it-sassari', 'Sassari', 'IT'),
  ('it-monza', 'Monza', 'IT'),
  ('it-syracuse', 'Syracuse', 'IT'),
  ('it-pescara', 'Pescara', 'IT'),
  ('it-bergamo', 'Bergamo', 'IT'),
  ('it-forli', 'Forlì', 'IT'),
  ('it-trento', 'Trento', 'IT'),
  ('it-vicenza', 'Vicenza', 'IT'),
  ('it-terni', 'Terni', 'IT'),
  ('it-bolzano', 'Bolzano', 'IT'),
  ('it-novara', 'Novara', 'IT'),
  ('it-piacenza', 'Piacenza', 'IT'),
  ('it-ancona', 'Ancona', 'IT'),
  ('it-andria', 'Andria', 'IT'),
  ('it-arezzo', 'Arezzo', 'IT'),
  ('it-udine', 'Udine', 'IT'),
  ('it-cesena', 'Cesena', 'IT'),
  ('it-lecce', 'Lecce', 'IT'),
  ('it-la-spezia', 'La Spezia', 'IT'),
  ('it-pisa', 'Pisa', 'IT'),

  -- Belgium
  ('be-charleroi', 'Charleroi', 'BE'),
  ('be-liege', 'Liège', 'BE'),
  ('be-brugge', 'Bruges', 'BE'),
  ('be-namur', 'Namur', 'BE'),
  ('be-leuven', 'Leuven', 'BE'),
  ('be-mons', 'Mons', 'BE'),
  ('be-aalst', 'Aalst', 'BE'),
  ('be-mechelen', 'Mechelen', 'BE'),
  ('be-la-louviere', 'La Louvière', 'BE'),
  ('be-kortrijk', 'Kortrijk', 'BE'),
  ('be-hasselt', 'Hasselt', 'BE'),
  ('be-ostend', 'Ostend', 'BE'),
  ('be-tournai', 'Tournai', 'BE'),
  ('be-genk', 'Genk', 'BE'),
  ('be-seraing', 'Seraing', 'BE'),
  ('be-roeselare', 'Roeselare', 'BE'),
  ('be-verviers', 'Verviers', 'BE'),
  ('be-mouscron', 'Mouscron', 'BE'),
  ('be-dendermonde', 'Dendermonde', 'BE'),
  ('be-beringen', 'Beringen', 'BE'),
  ('be-turnhout', 'Turnhout', 'BE'),
  ('be-sint-niklaas', 'Sint-Niklaas', 'BE'),
  ('be-vilvoorde', 'Vilvoorde', 'BE'),

  -- Austria
  ('at-innsbruck', 'Innsbruck', 'AT'),
  ('at-klagenfurt', 'Klagenfurt', 'AT'),
  ('at-villach', 'Villach', 'AT'),
  ('at-wels', 'Wels', 'AT'),
  ('at-sankt-polten', 'Sankt Pölten', 'AT'),
  ('at-dornbirn', 'Dornbirn', 'AT'),
  ('at-wiener-neustadt', 'Wiener Neustadt', 'AT'),
  ('at-steyr', 'Steyr', 'AT'),
  ('at-feldkirch', 'Feldkirch', 'AT'),
  ('at-bregenz', 'Bregenz', 'AT'),
  ('at-leonding', 'Leonding', 'AT'),
  ('at-klosterneuburg', 'Klosterneuburg', 'AT'),
  ('at-baden', 'Baden', 'AT'),
  ('at-wolfsberg', 'Wolfsberg', 'AT'),
  ('at-leoben', 'Leoben', 'AT'),
  ('at-krems', 'Krems', 'AT'),
  ('at-traiskirchen', 'Traiskirchen', 'AT'),
  ('at-amstetten', 'Amstetten', 'AT'),
  ('at-kapfenberg', 'Kapfenberg', 'AT'),
  ('at-halleina', 'Hallein', 'AT'),

  -- Switzerland
  ('ch-winterthur', 'Winterthur', 'CH'),
  ('ch-lucerne', 'Lucerne', 'CH'),
  ('ch-st-gallen', 'St. Gallen', 'CH'),
  ('ch-lugano', 'Lugano', 'CH'),
  ('ch-biel', 'Biel/Bienne', 'CH'),
  ('ch-thun', 'Thun', 'CH'),
  ('ch-koniz', 'Köniz', 'CH'),
  ('ch-la-chaux-de-fonds', 'La Chaux-de-Fonds', 'CH'),
  ('ch-schaffhausen', 'Schaffhausen', 'CH'),
  ('ch-fribourg', 'Fribourg', 'CH'),
  ('ch-chur', 'Chur', 'CH'),
  ('ch-neuchatel', 'Neuchâtel', 'CH'),
  ('ch-vernier', 'Vernier', 'CH'),
  ('ch-uster', 'Uster', 'CH'),
  ('ch-sion', 'Sion', 'CH'),
  ('ch-lancy', 'Lancy', 'CH'),
  ('ch-yverdon', 'Yverdon-les-Bains', 'CH'),
  ('ch-emmen', 'Emmen', 'CH'),
  ('ch-zug', 'Zug', 'CH'),
  ('ch-kriens', 'Kriens', 'CH'),
  ('ch-rapperswil', 'Rapperswil-Jona', 'CH'),
  ('ch-montreux', 'Montreux', 'CH'),
  ('ch-frauenfeld', 'Frauenfeld', 'CH'),

  -- Portugal
  ('pt-amadora', 'Amadora', 'PT'),
  ('pt-setubal', 'Setúbal', 'PT'),
  ('pt-funchal', 'Funchal', 'PT'),
  ('pt-almada', 'Almada', 'PT'),
  ('pt-aveiro', 'Aveiro', 'PT'),
  ('pt-viseu', 'Viseu', 'PT'),
  ('pt-leiria', 'Leiria', 'PT'),
  ('pt-faro', 'Faro', 'PT'),
  ('pt-evora', 'Évora', 'PT'),
  ('pt-guimaraes', 'Guimarães', 'PT'),
  ('pt-matosinhos', 'Matosinhos', 'PT'),
  ('pt-gondomar', 'Gondomar', 'PT'),
  ('pt-oeiras', 'Oeiras', 'PT'),
  ('pt-sintra', 'Sintra', 'PT'),
  ('pt-cascais', 'Cascais', 'PT'),
  ('pt-vila-nova-de-gaia', 'Vila Nova de Gaia', 'PT'),
  ('pt-maia', 'Maia', 'PT'),
  ('pt-loures', 'Loures', 'PT'),
  ('pt-odivelas', 'Odivelas', 'PT'),
  ('pt-barreiro', 'Barreiro', 'PT'),
  ('pt-seixal', 'Seixal', 'PT'),
  ('pt-portimao', 'Portimão', 'PT'),
  ('pt-covilha', 'Covilhã', 'PT'),
  ('pt-castelo-branco', 'Castelo Branco', 'PT'),

  -- Ireland
  ('ie-waterford', 'Waterford', 'IE'),
  ('ie-drogheda', 'Drogheda', 'IE'),
  ('ie-dundalk', 'Dundalk', 'IE'),
  ('ie-swords', 'Swords', 'IE'),
  ('ie-bray', 'Bray', 'IE'),
  ('ie-navan', 'Navan', 'IE'),
  ('ie-ennis', 'Ennis', 'IE'),
  ('ie-tralee', 'Tralee', 'IE'),
  ('ie-kilkenny', 'Kilkenny', 'IE'),
  ('ie-carlow', 'Carlow', 'IE'),
  ('ie-naas', 'Naas', 'IE'),
  ('ie-athlone', 'Athlone', 'IE'),
  ('ie-letterkenny', 'Letterkenny', 'IE'),
  ('ie-sligo', 'Sligo', 'IE'),
  ('ie-wexford', 'Wexford', 'IE'),
  ('ie-cloni', 'Clonmel', 'IE'),
  ('ie-mullingar', 'Mullingar', 'IE'),
  ('ie-celbridge', 'Celbridge', 'IE'),

  -- Sweden
  ('se-linkoping', 'Linköping', 'SE'),
  ('se-orebro', 'Örebro', 'SE'),
  ('se-vasteras', 'Västerås', 'SE'),
  ('se-helsingborg', 'Helsingborg', 'SE'),
  ('se-norrkoping', 'Norrköping', 'SE'),
  ('se-jonkoping', 'Jönköping', 'SE'),
  ('se-umea', 'Umeå', 'SE'),
  ('se-lund', 'Lund', 'SE'),
  ('se-boras', 'Borås', 'SE'),
  ('se-sundsvall', 'Sundsvall', 'SE'),
  ('se-gavle', 'Gävle', 'SE'),
  ('se-sodertalje', 'Södertälje', 'SE'),
  ('se-karlstad', 'Karlstad', 'SE'),
  ('se-vaxjo', 'Växjö', 'SE'),
  ('se-halmstad', 'Halmstad', 'SE'),
  ('se-eskilstuna', 'Eskilstuna', 'SE'),
  ('se-lulea', 'Luleå', 'SE'),
  ('se-trollhattan', 'Trollhättan', 'SE'),
  ('se-kalmar', 'Kalmar', 'SE'),
  ('se-skelleftea', 'Skellefteå', 'SE'),
  ('se-kristianstad', 'Kristianstad', 'SE'),
  ('se-falun', 'Falun', 'SE'),
  ('se-karlskrona', 'Karlskrona', 'SE'),

  -- Denmark
  ('dk-aalborg', 'Aalborg', 'DK'),
  ('dk-esbjerg', 'Esbjerg', 'DK'),
  ('dk-randers', 'Randers', 'DK'),
  ('dk-kolding', 'Kolding', 'DK'),
  ('dk-horsens', 'Horsens', 'DK'),
  ('dk-vejle', 'Vejle', 'DK'),
  ('dk-roskilde', 'Roskilde', 'DK'),
  ('dk-herning', 'Herning', 'DK'),
  ('dk-silkeborg', 'Silkeborg', 'DK'),
  ('dk-naestved', 'Næstved', 'DK'),
  ('dk-fredericia', 'Fredericia', 'DK'),
  ('dk-viborg', 'Viborg', 'DK'),
  ('dk-koge', 'Køge', 'DK'),
  ('dk-holstebro', 'Holstebro', 'DK'),
  ('dk-taastrup', 'Taastrup', 'DK'),
  ('dk-slagelse', 'Slagelse', 'DK'),
  ('dk-hilierod', 'Hillerød', 'DK'),
  ('dk-sonderborg', 'Sønderborg', 'DK'),
  ('dk-svendborg', 'Svendborg', 'DK'),
  ('dk-hjorring', 'Hjørring', 'DK'),

  -- Norway
  ('no-stavanger', 'Stavanger', 'NO'),
  ('no-drammen', 'Drammen', 'NO'),
  ('no-fredrikstad', 'Fredrikstad', 'NO'),
  ('no-kristiansand', 'Kristiansand', 'NO'),
  ('no-sandnes', 'Sandnes', 'NO'),
  ('no-tromso', 'Tromsø', 'NO'),
  ('no-sarpsborg', 'Sarpsborg', 'NO'),
  ('no-skien', 'Skien', 'NO'),
  ('no-alesund', 'Ålesund', 'NO'),
  ('no-sandefjord', 'Sandefjord', 'NO'),
  ('no-haugesund', 'Haugesund', 'NO'),
  ('no-tonsberg', 'Tønsberg', 'NO'),
  ('no-moss', 'Moss', 'NO'),
  ('no-porsgrunn', 'Porsgrunn', 'NO'),
  ('no-bodo', 'Bodø', 'NO'),
  ('no-arendal', 'Arendal', 'NO'),
  ('no-hamar', 'Hamar', 'NO'),
  ('no-larvik', 'Larvik', 'NO'),
  ('no-halden', 'Halden', 'NO'),
  ('no-lillehammer', 'Lillehammer', 'NO'),

  -- Finland
  ('fi-vantaa', 'Vantaa', 'FI'),
  ('fi-turku', 'Turku', 'FI'),
  ('fi-jyvaskyla', 'Jyväskylä', 'FI'),
  ('fi-lahti', 'Lahti', 'FI'),
  ('fi-kuopio', 'Kuopio', 'FI'),
  ('fi-pori', 'Pori', 'FI'),
  ('fi-kouvola', 'Kouvola', 'FI'),
  ('fi-joensuu', 'Joensuu', 'FI'),
  ('fi-lappeenranta', 'Lappeenranta', 'FI'),
  ('fi-hameenlinna', 'Hämeenlinna', 'FI'),
  ('fi-vaasa', 'Vaasa', 'FI'),
  ('fi-seinajoki', 'Seinäjoki', 'FI'),
  ('fi-rovaniemi', 'Rovaniemi', 'FI'),
  ('fi-mikkeli', 'Mikkeli', 'FI'),
  ('fi-kotka', 'Kotka', 'FI'),
  ('fi-salo', 'Salo', 'FI'),
  ('fi-porvoo', 'Porvoo', 'FI'),
  ('fi-kokkola', 'Kokkola', 'FI'),
  ('fi-hyvinkaa', 'Hyvinkää', 'FI'),
  ('fi-nurmijarvi', 'Nurmijärvi', 'FI'),

  -- Poland
  ('pl-lodz', 'Łódź', 'PL'),
  ('pl-krakow', 'Kraków', 'PL'),
  ('pl-wroclaw', 'Wrocław', 'PL'),
  ('pl-poznan', 'Poznań', 'PL'),
  ('pl-gdansk', 'Gdańsk', 'PL'),
  ('pl-szczecin', 'Szczecin', 'PL'),
  ('pl-bydgoszcz', 'Bydgoszcz', 'PL'),
  ('pl-lublin', 'Lublin', 'PL'),
  ('pl-bialystok', 'Białystok', 'PL'),
  ('pl-katowice', 'Katowice', 'PL'),
  ('pl-gdynia', 'Gdynia', 'PL'),
  ('pl-czestochowa', 'Częstochowa', 'PL'),
  ('pl-radom', 'Radom', 'PL'),
  ('pl-sosnowiec', 'Sosnowiec', 'PL'),
  ('pl-torun', 'Toruń', 'PL'),
  ('pl-kielce', 'Kielce', 'PL'),
  ('pl-rzeszow', 'Rzeszów', 'PL'),
  ('pl-gliwick', 'Gliwice', 'PL'),
  ('pl-zabrze', 'Zabrze', 'PL'),
  ('pl-olsztyn', 'Olsztyn', 'PL'),
  ('pl-bielsko-biala', 'Bielsko-Biała', 'PL'),
  ('pl-bytom', 'Bytom', 'PL'),
  ('pl-zielona-gora', 'Zielona Góra', 'PL'),
  ('pl-rybnik', 'Rybnik', 'PL'),
  ('pl-ruda-slaska', 'Ruda Śląska', 'PL'),
  ('pl-opole', 'Opole', 'PL'),
  ('pl-tychy', 'Tychy', 'PL'),
  ('pl-gorzow', 'Gorzów Wielkopolski', 'PL'),
  ('pl-elblag', 'Elbląg', 'PL'),
  ('pl-plock', 'Płock', 'PL'),
  ('pl-walbrzych', 'Wałbrzych', 'PL'),
  ('pl-wloclawek', 'Włocławek', 'PL'),
  ('pl-tarnow', 'Tarnów', 'PL'),
  ('pl-chorzow', 'Chorzów', 'PL'),
  ('pl-koszalin', 'Koszalin', 'PL'),
  ('pl-kalisz', 'Kalisz', 'PL'),
  ('pl-legnica', 'Legnica', 'PL'),

  -- United Kingdom (extra)
  ('gb-southampton', 'Southampton', 'GB'),
  ('gb-portsmouth', 'Portsmouth', 'GB'),
  ('gb-brighton', 'Brighton', 'GB'),
  ('gb-plymouth', 'Plymouth', 'GB'),
  ('gb-derby', 'Derby', 'GB'),
  ('gb-stoke', 'Stoke-on-Trent', 'GB'),
  ('gb-wolverhampton', 'Wolverhampton', 'GB'),
  ('gb-coventry', 'Coventry', 'GB'),
  ('gb-sunderland', 'Sunderland', 'GB'),
  ('gb-milton-keynes', 'Milton Keynes', 'GB'),
  ('gb-northampton', 'Northampton', 'GB'),
  ('gb-norwich', 'Norwich', 'GB'),
  ('gb-swindon', 'Swindon', 'GB'),
  ('gb-swansea', 'Swansea', 'GB'),
  ('gb-aberdeen', 'Aberdeen', 'GB'),
  ('gb-dundee', 'Dundee', 'GB'),
  ('gb-york', 'York', 'GB'),
  ('gb-bath', 'Bath', 'GB'),
  ('gb-exeter', 'Exeter', 'GB'),
  ('gb-chester', 'Chester', 'GB'),
  ('gb-ipswich', 'Ipswich', 'GB'),
  ('gb-peterborough', 'Peterborough', 'GB'),
  ('gb-luton', 'Luton', 'GB'),
  ('gb-southend', 'Southend-on-Sea', 'GB'),
  ('gb-bournemouth', 'Bournemouth', 'GB'),
  ('gb-middlesbrough', 'Middlesbrough', 'GB'),
  ('gb-blackpool', 'Blackpool', 'GB'),
  ('gb-preston', 'Preston', 'GB'),
  ('gb-huddersfield', 'Huddersfield', 'GB'),
  ('gb-bradford', 'Bradford', 'GB'),
  ('gb-hull', 'Hull', 'GB'),
  ('gb-warrington', 'Warrington', 'GB'),
  ('gb-slough', 'Slough', 'GB'),
  ('gb-watford', 'Watford', 'GB'),
  ('gb-guildford', 'Guildford', 'GB'),

  -- United States (extra metros)
  ('us-san-francisco', 'San Francisco', 'US'),
  ('us-baltimore', 'Baltimore', 'US'),
  ('us-milwaukee', 'Milwaukee', 'US'),
  ('us-albuquerque', 'Albuquerque', 'US'),
  ('us-tucson', 'Tucson', 'US'),
  ('us-fresno', 'Fresno', 'US'),
  ('us-mesa', 'Mesa', 'US'),
  ('us-atlanta', 'Atlanta', 'US'),
  ('us-colorado-springs', 'Colorado Springs', 'US'),
  ('us-virginia-beach', 'Virginia Beach', 'US'),
  ('us-omaha', 'Omaha', 'US'),
  ('us-oakland', 'Oakland', 'US'),
  ('us-tulsa', 'Tulsa', 'US'),
  ('us-arlington', 'Arlington', 'US'),
  ('us-new-orleans', 'New Orleans', 'US'),
  ('us-wichita', 'Wichita', 'US'),
  ('us-cleveland', 'Cleveland', 'US'),
  ('us-bakersfield', 'Bakersfield', 'US'),
  ('us-aurora', 'Aurora', 'US'),
  ('us-anaheim', 'Anaheim', 'US'),
  ('us-honolulu', 'Honolulu', 'US'),
  ('us-santa-ana', 'Santa Ana', 'US'),
  ('us-riverside', 'Riverside', 'US'),
  ('us-corpus-christi', 'Corpus Christi', 'US'),
  ('us-lexington', 'Lexington', 'US'),
  ('us-stockton', 'Stockton', 'US'),
  ('us-henderson', 'Henderson', 'US'),
  ('us-saint-paul', 'Saint Paul', 'US'),
  ('us-st-louis', 'St. Louis', 'US'),
  ('us-cincinnati', 'Cincinnati', 'US'),
  ('us-anchorage', 'Anchorage', 'US'),
  ('us-greensboro', 'Greensboro', 'US'),
  ('us-plano', 'Plano', 'US'),
  ('us-newark', 'Newark', 'US'),
  ('us-lincoln', 'Lincoln', 'US'),
  ('us-orlando', 'Orlando', 'US'),
  ('us-irvine', 'Irvine', 'US'),
  ('us-durham', 'Durham', 'US'),
  ('us-chula-vista', 'Chula Vista', 'US'),
  ('us-toledo', 'Toledo', 'US'),
  ('us-fort-wayne', 'Fort Wayne', 'US'),
  ('us-st-petersburg', 'St. Petersburg', 'US'),
  ('us-laredo', 'Laredo', 'US'),
  ('us-jersey-city', 'Jersey City', 'US'),
  ('us-chandler', 'Chandler', 'US'),
  ('us-madison', 'Madison', 'US'),
  ('us-lubbock', 'Lubbock', 'US'),
  ('us-scottsdale', 'Scottsdale', 'US'),
  ('us-reno', 'Reno', 'US'),
  ('us-buffalo', 'Buffalo', 'US'),
  ('us-gilbert', 'Gilbert', 'US'),
  ('us-glendale', 'Glendale', 'US'),
  ('us-north-las-vegas', 'North Las Vegas', 'US'),
  ('us-winston-salem', 'Winston-Salem', 'US'),
  ('us-chesapeake', 'Chesapeake', 'US'),
  ('us-norfolk', 'Norfolk', 'US'),
  ('us-fremont', 'Fremont', 'US'),
  ('us-garland', 'Garland', 'US'),
  ('us-irving', 'Irving', 'US'),
  ('us-hialeah', 'Hialeah', 'US'),
  ('us-richmond', 'Richmond', 'US'),
  ('us-boise', 'Boise', 'US'),
  ('us-spokane', 'Spokane', 'US'),
  ('us-baton-rouge', 'Baton Rouge', 'US'),

  -- Canada (extra)
  ('ca-edmonton', 'Edmonton', 'CA'),
  ('ca-mississauga', 'Mississauga', 'CA'),
  ('ca-brampton', 'Brampton', 'CA'),
  ('ca-surrey', 'Surrey', 'CA'),
  ('ca-laval', 'Laval', 'CA'),
  ('ca-london', 'London', 'CA'),
  ('ca-markham', 'Markham', 'CA'),
  ('ca-vaughan', 'Vaughan', 'CA'),
  ('ca-gatineau', 'Gatineau', 'CA'),
  ('ca-saskatoon', 'Saskatoon', 'CA'),
  ('ca-longueuil', 'Longueuil', 'CA'),
  ('ca-burnaby', 'Burnaby', 'CA'),
  ('ca-regina', 'Regina', 'CA'),
  ('ca-richmond', 'Richmond', 'CA'),
  ('ca-richmond-hill', 'Richmond Hill', 'CA'),
  ('ca-oakville', 'Oakville', 'CA'),
  ('ca-burlington', 'Burlington', 'CA'),
  ('ca-oshawa', 'Oshawa', 'CA'),
  ('ca-sherbrooke', 'Sherbrooke', 'CA'),
  ('ca-barrie', 'Barrie', 'CA'),
  ('ca-abbotsford', 'Abbotsford', 'CA'),
  ('ca-coquitlam', 'Coquitlam', 'CA'),
  ('ca-kelowna', 'Kelowna', 'CA'),
  ('ca-guelph', 'Guelph', 'CA'),
  ('ca-cambridge', 'Cambridge', 'CA'),
  ('ca-whitby', 'Whitby', 'CA'),
  ('ca-ajax', 'Ajax', 'CA'),
  ('ca-thunder-bay', 'Thunder Bay', 'CA'),
  ('ca-waterloo', 'Waterloo', 'CA'),
  ('ca-st-catharines', 'St. Catharines', 'CA'),

  -- Australia (extra)
  ('au-newcastle', 'Newcastle', 'AU'),
  ('au-wollongong', 'Wollongong', 'AU'),
  ('au-geelong', 'Geelong', 'AU'),
  ('au-townsville', 'Townsville', 'AU'),
  ('au-cairns', 'Cairns', 'AU'),
  ('au-toowoomba', 'Toowoomba', 'AU'),
  ('au-darwin', 'Darwin', 'AU'),
  ('au-ballarat', 'Ballarat', 'AU'),
  ('au-bendigo', 'Bendigo', 'AU'),
  ('au-launceston', 'Launceston', 'AU'),
  ('au-mackay', 'Mackay', 'AU'),
  ('au-rockhampton', 'Rockhampton', 'AU'),
  ('au-bunbury', 'Bunbury', 'AU'),
  ('au-bundaberg', 'Bundaberg', 'AU'),
  ('au-wagga-wagga', 'Wagga Wagga', 'AU'),
  ('au-hervey-bay', 'Hervey Bay', 'AU'),
  ('au-mildura', 'Mildura', 'AU'),
  ('au-shepparton', 'Shepparton', 'AU'),
  ('au-port-macquarie', 'Port Macquarie', 'AU'),
  ('au-gladstone', 'Gladstone', 'AU'),
  ('au-tramel', 'Traralgon', 'AU'),
  ('au-orange', 'Orange', 'AU'),
  ('au-dubbo', 'Dubbo', 'AU'),
  ('au-geraldton', 'Geraldton', 'AU'),
  ('au-nowra', 'Nowra', 'AU'),
  ('au-bathurst', 'Bathurst', 'AU'),
  ('au-warrnambool', 'Warrnambool', 'AU'),
  ('au-albany', 'Albany', 'AU'),

  -- Brazil
  ('br-fortaleza', 'Fortaleza', 'BR'),
  ('br-belo-horizonte', 'Belo Horizonte', 'BR'),
  ('br-manaus', 'Manaus', 'BR'),
  ('br-curitiba', 'Curitiba', 'BR'),
  ('br-recife', 'Recife', 'BR'),
  ('br-porto-alegre', 'Porto Alegre', 'BR'),
  ('br-belem', 'Belém', 'BR'),
  ('br-goiania', 'Goiânia', 'BR'),
  ('br-guarulhos', 'Guarulhos', 'BR'),
  ('br-campinas', 'Campinas', 'BR'),
  ('br-sao-goncalo', 'São Gonçalo', 'BR'),
  ('br-sao-luis', 'São Luís', 'BR'),
  ('br-maceio', 'Maceió', 'BR'),
  ('br-duque-de-caxias', 'Duque de Caxias', 'BR'),
  ('br-natal', 'Natal', 'BR'),
  ('br-teresina', 'Teresina', 'BR'),
  ('br-campo-grande', 'Campo Grande', 'BR'),
  ('br-nova-iguacu', 'Nova Iguaçu', 'BR'),
  ('br-sao-bernardo', 'São Bernardo do Campo', 'BR'),
  ('br-joao-pessoa', 'João Pessoa', 'BR'),
  ('br-santo-andre', 'Santo André', 'BR'),
  ('br-osasco', 'Osasco', 'BR'),
  ('br-jaboatao', 'Jaboatão', 'BR'),
  ('br-sao-jose-dos-campos', 'São José dos Campos', 'BR'),
  ('br-ribeirao-preto', 'Ribeirão Preto', 'BR'),
  ('br-uberlandia', 'Uberlândia', 'BR'),
  ('br-sorocaba', 'Sorocaba', 'BR'),
  ('br-contagem', 'Contagem', 'BR'),
  ('br-aracaju', 'Aracaju', 'BR'),
  ('br-feira-de-santana', 'Feira de Santana', 'BR'),
  ('br-cuiaba', 'Cuiabá', 'BR'),
  ('br-joinville', 'Joinville', 'BR'),
  ('br-juiz-de-fora', 'Juiz de Fora', 'BR'),
  ('br-londrina', 'Londrina', 'BR'),
  ('br-niteroi', 'Niterói', 'BR'),
  ('br-americana', 'Americana', 'BR'),

  -- Mexico
  ('mx-puebla', 'Puebla', 'MX'),
  ('mx-tijuana', 'Tijuana', 'MX'),
  ('mx-leon', 'León', 'MX'),
  ('mx-juarez', 'Ciudad Juárez', 'MX'),
  ('mx-zapopan', 'Zapopan', 'MX'),
  ('mx-merida', 'Mérida', 'MX'),
  ('mx-san-luis-potosi', 'San Luis Potosí', 'MX'),
  ('mx-aguascalientes', 'Aguascalientes', 'MX'),
  ('mx-hermosillo', 'Hermosillo', 'MX'),
  ('mx-saltillo', 'Saltillo', 'MX'),
  ('mx-mexicali', 'Mexicali', 'MX'),
  ('mx-culiacan', 'Culiacán', 'MX'),
  ('mx-acapulco', 'Acapulco', 'MX'),
  ('mx-tlalnepantla', 'Tlalnepantla', 'MX'),
  ('mx-cancun', 'Cancún', 'MX'),
  ('mx-queretaro', 'Querétaro', 'MX'),
  ('mx-chihuahua', 'Chihuahua', 'MX'),
  ('mx-morelia', 'Morelia', 'MX'),
  ('mx-reynosa', 'Reynosa', 'MX'),
  ('mx-torreon', 'Torreón', 'MX'),
  ('mx-toluca', 'Toluca', 'MX'),
  ('mx-durango', 'Durango', 'MX'),
  ('mx-veracruz', 'Veracruz', 'MX'),
  ('mx-villahermosa', 'Villahermosa', 'MX'),
  ('mx-xalapa', 'Xalapa', 'MX'),
  ('mx-tuxtla', 'Tuxtla Gutiérrez', 'MX'),
  ('mx-mazatlan', 'Mazatlán', 'MX'),
  ('mx-oaxaca', 'Oaxaca', 'MX'),
  ('mx-tampico', 'Tampico', 'MX'),
  ('mx-celaya', 'Celaya', 'MX'),

  -- Japan
  ('jp-yokohama', 'Yokohama', 'JP'),
  ('jp-osaka', 'Osaka', 'JP'),
  ('jp-nagoya', 'Nagoya', 'JP'),
  ('jp-sapporo', 'Sapporo', 'JP'),
  ('jp-fukuoka', 'Fukuoka', 'JP'),
  ('jp-kobe', 'Kobe', 'JP'),
  ('jp-kyoto', 'Kyoto', 'JP'),
  ('jp-kawasaki', 'Kawasaki', 'JP'),
  ('jp-saitama', 'Saitama', 'JP'),
  ('jp-hiroshima', 'Hiroshima', 'JP'),
  ('jp-sendai', 'Sendai', 'JP'),
  ('jp-chiba', 'Chiba', 'JP'),
  ('jp-kitakyushu', 'Kitakyushu', 'JP'),
  ('jp-sakai', 'Sakai', 'JP'),
  ('jp-niigata', 'Niigata', 'JP'),
  ('jp-hamamatsu', 'Hamamatsu', 'JP'),
  ('jp-kumamoto', 'Kumamoto', 'JP'),
  ('jp-sagamihara', 'Sagamihara', 'JP'),
  ('jp-shizuoka', 'Shizuoka', 'JP'),
  ('jp-okayama', 'Okayama', 'JP'),
  ('jp-kagoshima', 'Kagoshima', 'JP'),
  ('jp-funabashi', 'Funabashi', 'JP'),
  ('jp-hachioji', 'Hachioji', 'JP'),
  ('jp-matsuyama', 'Matsuyama', 'JP'),
  ('jp-kawaguchi', 'Kawaguchi', 'JP'),
  ('jp-ichikawa', 'Ichikawa', 'JP'),
  ('jp-nagasaki', 'Nagasaki', 'JP'),
  ('jp-utsunomiya', 'Utsunomiya', 'JP'),
  ('jp-kanazawa', 'Kanazawa', 'JP'),
  ('jp-naha', 'Naha', 'JP'),

  -- South Korea
  ('kr-busan', 'Busan', 'KR'),
  ('kr-incheon', 'Incheon', 'KR'),
  ('kr-daegu', 'Daegu', 'KR'),
  ('kr-daejeon', 'Daejeon', 'KR'),
  ('kr-gwangju', 'Gwangju', 'KR'),
  ('kr-ulsan', 'Ulsan', 'KR'),
  ('kr-suwon', 'Suwon', 'KR'),
  ('kr-changwon', 'Changwon', 'KR'),
  ('kr-goyang', 'Goyang', 'KR'),
  ('kr-yongin', 'Yongin', 'KR'),
  ('kr-seongnam', 'Seongnam', 'KR'),
  ('kr-bucheon', 'Bucheon', 'KR'),
  ('kr-ansan', 'Ansan', 'KR'),
  ('kr-anyang', 'Anyang', 'KR'),
  ('kr-jeonju', 'Jeonju', 'KR'),
  ('kr-cheonan', 'Cheonan', 'KR'),
  ('kr-namyangju', 'Namyangju', 'KR'),
  ('kr-hwaseong', 'Hwaseong', 'KR'),
  ('kr-gimhae', 'Gimhae', 'KR'),
  ('kr-pyeongtaek', 'Pyeongtaek', 'KR'),

  -- China (major metros)
  ('cn-shanghai', 'Shanghai', 'CN'),
  ('cn-beijing', 'Beijing', 'CN'),
  ('cn-guangzhou', 'Guangzhou', 'CN'),
  ('cn-shenzhen', 'Shenzhen', 'CN'),
  ('cn-chengdu', 'Chengdu', 'CN'),
  ('cn-tianjin', 'Tianjin', 'CN'),
  ('cn-wuhan', 'Wuhan', 'CN'),
  ('cn-dongguan', 'Dongguan', 'CN'),
  ('cn-chongqing', 'Chongqing', 'CN'),
  ('cn-nanjing', 'Nanjing', 'CN'),
  ('cn-xian', 'Xi''an', 'CN'),
  ('cn-hangzhou', 'Hangzhou', 'CN'),
  ('cn-shenyang', 'Shenyang', 'CN'),
  ('cn-qingdao', 'Qingdao', 'CN'),
  ('cn-dalian', 'Dalian', 'CN'),
  ('cn-suzhou', 'Suzhou', 'CN'),
  ('cn-zhengzhou', 'Zhengzhou', 'CN'),
  ('cn-changsha', 'Changsha', 'CN'),
  ('cn-kunming', 'Kunming', 'CN'),
  ('cn-xiamen', 'Xiamen', 'CN'),
  ('cn-ningbo', 'Ningbo', 'CN'),
  ('cn-hefei', 'Hefei', 'CN'),
  ('cn-fuzhou', 'Fuzhou', 'CN'),
  ('cn-harbin', 'Harbin', 'CN'),
  ('cn-jinan', 'Jinan', 'CN'),
  ('cn-wuxi', 'Wuxi', 'CN'),
  ('cn-foshan', 'Foshan', 'CN'),
  ('cn-nanchang', 'Nanchang', 'CN'),
  ('cn-changchun', 'Changchun', 'CN'),
  ('cn-wenzhou', 'Wenzhou', 'CN'),

  -- Turkey
  ('tr-ankara', 'Ankara', 'TR'),
  ('tr-izmir', 'İzmir', 'TR'),
  ('tr-bursa', 'Bursa', 'TR'),
  ('tr-adana', 'Adana', 'TR'),
  ('tr-gaziantep', 'Gaziantep', 'TR'),
  ('tr-konya', 'Konya', 'TR'),
  ('tr-antalya', 'Antalya', 'TR'),
  ('tr-kayseri', 'Kayseri', 'TR'),
  ('tr-mersin', 'Mersin', 'TR'),
  ('tr-eskisehir', 'Eskişehir', 'TR'),
  ('tr-diyarbakir', 'Diyarbakır', 'TR'),
  ('tr-samsun', 'Samsun', 'TR'),
  ('tr-denizli', 'Denizli', 'TR'),
  ('tr-sanliurfa', 'Şanlıurfa', 'TR'),
  ('tr-malatya', 'Malatya', 'TR'),
  ('tr-erzurum', 'Erzurum', 'TR'),
  ('tr-van', 'Van', 'TR'),
  ('tr-batman', 'Batman', 'TR'),
  ('tr-elazig', 'Elazığ', 'TR'),
  ('tr-manisa', 'Manisa', 'TR'),
  ('tr-sivas', 'Sivas', 'TR'),
  ('tr-gebze', 'Gebze', 'TR'),
  ('tr-balikesir', 'Balıkesir', 'TR'),
  ('tr-kahramanmaras', 'Kahramanmaraş', 'TR'),
  ('tr-aydin', 'Aydın', 'TR'),

  -- South Africa
  ('za-cape-town', 'Cape Town', 'ZA'),
  ('za-durban', 'Durban', 'ZA'),
  ('za-pretoria', 'Pretoria', 'ZA'),
  ('za-port-elizabeth', 'Gqeberha / Port Elizabeth', 'ZA'),
  ('za-bloemfontein', 'Bloemfontein', 'ZA'),
  ('za-east-london', 'East London', 'ZA'),
  ('za-pietermaritzburg', 'Pietermaritzburg', 'ZA'),
  ('za-polokwane', 'Polokwane', 'ZA'),
  ('za-nelspruit', 'Mbombela / Nelspruit', 'ZA'),
  ('za-kimberley', 'Kimberley', 'ZA'),
  ('za-rustenburg', 'Rustenburg', 'ZA'),
  ('za-welkom', 'Welkom', 'ZA'),
  ('za-newcastle', 'Newcastle', 'ZA'),
  ('za-krugersdorp', 'Krugersdorp', 'ZA'),
  ('za-vereeniging', 'Vereeniging', 'ZA'),
  ('za-soweto', 'Soweto', 'ZA'),
  ('za-centurion', 'Centurion', 'ZA'),
  ('za-sandton', 'Sandton', 'ZA'),
  ('za-stellenbosch', 'Stellenbosch', 'ZA'),
  ('za-george', 'George', 'ZA'),

  -- Nigeria
  ('ng-abuja', 'Abuja', 'NG'),
  ('ng-kano', 'Kano', 'NG'),
  ('ng-ibadan', 'Ibadan', 'NG'),
  ('ng-port-harcourt', 'Port Harcourt', 'NG'),
  ('ng-benin-city', 'Benin City', 'NG'),
  ('ng-kaduna', 'Kaduna', 'NG'),
  ('ng-maiduguri', 'Maiduguri', 'NG'),
  ('ng-zaria', 'Zaria', 'NG'),
  ('ng-aba', 'Aba', 'NG'),
  ('ng-jos', 'Jos', 'NG'),
  ('ng-ilorin', 'Ilorin', 'NG'),
  ('ng-oyo', 'Oyo', 'NG'),
  ('ng-enugu', 'Enugu', 'NG'),
  ('ng-abeokuta', 'Abeokuta', 'NG'),
  ('ng-onitsha', 'Onitsha', 'NG'),
  ('ng-warri', 'Warri', 'NG'),
  ('ng-sokoto', 'Sokoto', 'NG'),
  ('ng-calabar', 'Calabar', 'NG'),
  ('ng-uyo', 'Uyo', 'NG'),

  -- Egypt
  ('eg-alexandria', 'Alexandria', 'EG'),
  ('eg-giza', 'Giza', 'EG'),
  ('eg-shubra-el-kheima', 'Shubra El Kheima', 'EG'),
  ('eg-port-said', 'Port Said', 'EG'),
  ('eg-suez', 'Suez', 'EG'),
  ('eg-luxor', 'Luxor', 'EG'),
  ('eg-mansoura', 'Mansoura', 'EG'),
  ('eg-tanta', 'Tanta', 'EG'),
  ('eg-asyut', 'Asyut', 'EG'),
  ('eg-ismailia', 'Ismailia', 'EG'),
  ('eg-fayoum', 'Fayoum', 'EG'),
  ('eg-zagazig', 'Zagazig', 'EG'),
  ('eg-damietta', 'Damietta', 'EG'),
  ('eg-minya', 'Minya', 'EG'),
  ('eg-sohag', 'Sohag', 'EG'),
  ('eg-qena', 'Qena', 'EG'),
  ('eg-beni-suef', 'Beni Suef', 'EG'),
  ('eg-hurghada', 'Hurghada', 'EG'),
  ('eg-sharm-el-sheikh', 'Sharm El Sheikh', 'EG'),

  -- Indonesia
  ('id-surabaya', 'Surabaya', 'ID'),
  ('id-bandung', 'Bandung', 'ID'),
  ('id-medan', 'Medan', 'ID'),
  ('id-bekasi', 'Bekasi', 'ID'),
  ('id-depok', 'Depok', 'ID'),
  ('id-tangerang', 'Tangerang', 'ID'),
  ('id-semarang', 'Semarang', 'ID'),
  ('id-palembang', 'Palembang', 'ID'),
  ('id-makassar', 'Makassar', 'ID'),
  ('id-south-tangerang', 'South Tangerang', 'ID'),
  ('id-batam', 'Batam', 'ID'),
  ('id-bogor', 'Bogor', 'ID'),
  ('id-pekanbaru', 'Pekanbaru', 'ID'),
  ('id-bandar-lampung', 'Bandar Lampung', 'ID'),
  ('id-padang', 'Padang', 'ID'),
  ('id-malang', 'Malang', 'ID'),
  ('id-denpasar', 'Denpasar', 'ID'),
  ('id-samarinda', 'Samarinda', 'ID'),
  ('id-tasikmalaya', 'Tasikmalaya', 'ID'),
  ('id-pontianak', 'Pontianak', 'ID'),
  ('id-balikpapan', 'Balikpapan', 'ID'),
  ('id-jambi', 'Jambi', 'ID'),
  ('id-cirebon', 'Cirebon', 'ID'),
  ('id-surakarta', 'Surakarta', 'ID'),
  ('id-manado', 'Manado', 'ID'),

  -- Malaysia
  ('my-johor-bahru', 'Johor Bahru', 'MY'),
  ('my-ipoh', 'Ipoh', 'MY'),
  ('my-shah-alam', 'Shah Alam', 'MY'),
  ('my-petaling-jaya', 'Petaling Jaya', 'MY'),
  ('my-klang', 'Klang', 'MY'),
  ('my-george-town', 'George Town', 'MY'),
  ('my-kota-kinabalu', 'Kota Kinabalu', 'MY'),
  ('my-kuching', 'Kuching', 'MY'),
  ('my-seremban', 'Seremban', 'MY'),
  ('my-malacca', 'Malacca', 'MY'),
  ('my-alor-setar', 'Alor Setar', 'MY'),
  ('my-miri', 'Miri', 'MY'),
  ('my-kuala-terengganu', 'Kuala Terengganu', 'MY'),
  ('my-kota-bharu', 'Kota Bharu', 'MY'),
  ('my-sandakan', 'Sandakan', 'MY'),
  ('my-taiping', 'Taiping', 'MY'),
  ('my-kulai', 'Kulai', 'MY'),
  ('my-sungai-petani', 'Sungai Petani', 'MY'),
  ('my-subang-jaya', 'Subang Jaya', 'MY'),
  ('my-ampang', 'Ampang', 'MY'),

  -- Thailand
  ('th-chiang-mai', 'Chiang Mai', 'TH'),
  ('th-pattaya', 'Pattaya', 'TH'),
  ('th-hat-yai', 'Hat Yai', 'TH'),
  ('th-nakhon-ratchasima', 'Nakhon Ratchasima', 'TH'),
  ('th-udon-thani', 'Udon Thani', 'TH'),
  ('th-khon-kaen', 'Khon Kaen', 'TH'),
  ('th-chonburi', 'Chonburi', 'TH'),
  ('th-nakhon-si-thammarat', 'Nakhon Si Thammarat', 'TH'),
  ('th-songkhla', 'Songkhla', 'TH'),
  ('th-surat-thani', 'Surat Thani', 'TH'),
  ('th-phuket', 'Phuket', 'TH'),
  ('th-chiang-rai', 'Chiang Rai', 'TH'),
  ('th-lampang', 'Lampang', 'TH'),
  ('th-rayong', 'Rayong', 'TH'),
  ('th-nakhon-pathom', 'Nakhon Pathom', 'TH'),
  ('th-nonthaburi', 'Nonthaburi', 'TH'),
  ('th-pak-kret', 'Pak Kret', 'TH'),
  ('th-hatyai', 'Hat Yai', 'TH'),
  ('th-samut-prakan', 'Samut Prakan', 'TH'),
  ('th-ayutthaya', 'Ayutthaya', 'TH'),

  -- Philippines
  ('ph-cebu', 'Cebu City', 'PH'),
  ('ph-davao', 'Davao City', 'PH'),
  ('ph-quezon-city', 'Quezon City', 'PH'),
  ('ph-caloocan', 'Caloocan', 'PH'),
  ('ph-zamboanga', 'Zamboanga City', 'PH'),
  ('ph-antipolo', 'Antipolo', 'PH'),
  ('ph-pasig', 'Pasig', 'PH'),
  ('ph-taguig', 'Taguig', 'PH'),
  ('ph-cagayan-de-oro', 'Cagayan de Oro', 'PH'),
  ('ph-paranaque', 'Parañaque', 'PH'),
  ('ph-dasmarinas', 'Dasmariñas', 'PH'),
  ('ph-valenzuela', 'Valenzuela', 'PH'),
  ('ph-bacoor', 'Bacoor', 'PH'),
  ('ph-general-santos', 'General Santos', 'PH'),
  ('ph-las-pinas', 'Las Piñas', 'PH'),
  ('ph-makati', 'Makati', 'PH'),
  ('ph-bacolod', 'Bacolod', 'PH'),
  ('ph-muntinlupa', 'Muntinlupa', 'PH'),
  ('ph-san-jose-del-monte', 'San Jose del Monte', 'PH'),
  ('ph-iloilo', 'Iloilo City', 'PH'),

  -- New Zealand
  ('nz-auckland', 'Auckland', 'NZ'),
  ('nz-christchurch', 'Christchurch', 'NZ'),
  ('nz-wellington', 'Wellington', 'NZ'),
  ('nz-hamilton', 'Hamilton', 'NZ'),
  ('nz-tauranga', 'Tauranga', 'NZ'),
  ('nz-napier', 'Napier', 'NZ'),
  ('nz-palmerston-north', 'Palmerston North', 'NZ'),
  ('nz-nelson', 'Nelson', 'NZ'),
  ('nz-rotorua', 'Rotorua', 'NZ'),
  ('nz-new-plymouth', 'New Plymouth', 'NZ'),
  ('nz-whangarei', 'Whangārei', 'NZ'),
  ('nz-invercargill', 'Invercargill', 'NZ'),
  ('nz-whanganui', 'Whanganui', 'NZ'),
  ('nz-gisborne', 'Gisborne', 'NZ'),
  ('nz-blenheim', 'Blenheim', 'NZ'),
  ('nz-timaru', 'Timaru', 'NZ'),
  ('nz-taupo', 'Taupō', 'NZ'),
  ('nz-masterton', 'Masterton', 'NZ'),
  ('nz-levin', 'Levin', 'NZ'),
  ('nz-ashburton', 'Ashburton', 'NZ'),

  -- Argentina
  ('ar-cordoba', 'Córdoba', 'AR'),
  ('ar-rosario', 'Rosario', 'AR'),
  ('ar-mendoza', 'Mendoza', 'AR'),
  ('ar-tucuman', 'San Miguel de Tucumán', 'AR'),
  ('ar-la-plata', 'La Plata', 'AR'),
  ('ar-mar-del-plata', 'Mar del Plata', 'AR'),
  ('ar-salta', 'Salta', 'AR'),
  ('ar-santa-fe', 'Santa Fe', 'AR'),
  ('ar-san-juan', 'San Juan', 'AR'),
  ('ar-resistencia', 'Resistencia', 'AR'),
  ('ar-santiago-del-estero', 'Santiago del Estero', 'AR'),
  ('ar-corrientes', 'Corrientes', 'AR'),
  ('ar-bahia-blanca', 'Bahía Blanca', 'AR'),
  ('ar-posadas', 'Posadas', 'AR'),
  ('ar-neuquen', 'Neuquén', 'AR'),

  -- Chile
  ('cl-valparaiso', 'Valparaíso', 'CL'),
  ('cl-concepcion', 'Concepción', 'CL'),
  ('cl-la-serena', 'La Serena', 'CL'),
  ('cl-antofagasta', 'Antofagasta', 'CL'),
  ('cl-temuco', 'Temuco', 'CL'),
  ('cl-rancagua', 'Rancagua', 'CL'),
  ('cl-talca', 'Talca', 'CL'),
  ('cl-arica', 'Arica', 'CL'),
  ('cl-iquique', 'Iquique', 'CL'),
  ('cl-puerto-montt', 'Puerto Montt', 'CL'),
  ('cl-coquimbo', 'Coquimbo', 'CL'),
  ('cl-chillan', 'Chillán', 'CL'),
  ('cl-calama', 'Calama', 'CL'),
  ('cl-osorno', 'Osorno', 'CL'),
  ('cl-valdivia', 'Valdivia', 'CL'),

  -- Colombia
  ('co-medellin', 'Medellín', 'CO'),
  ('co-cali', 'Cali', 'CO'),
  ('co-barranquilla', 'Barranquilla', 'CO'),
  ('co-cartagena', 'Cartagena', 'CO'),
  ('co-cucuta', 'Cúcuta', 'CO'),
  ('co-bucaramanga', 'Bucaramanga', 'CO'),
  ('co-pereira', 'Pereira', 'CO'),
  ('co-santa-marta', 'Santa Marta', 'CO'),
  ('co-ibague', 'Ibagué', 'CO'),
  ('co-pasto', 'Pasto', 'CO'),
  ('co-manizales', 'Manizales', 'CO'),
  ('co-neiva', 'Neiva', 'CO'),
  ('co-villavicencio', 'Villavicencio', 'CO'),
  ('co-armenia', 'Armenia', 'CO'),
  ('co-soledad', 'Soledad', 'CO'),

  -- Peru
  ('pe-arequipa', 'Arequipa', 'PE'),
  ('pe-trujillo', 'Trujillo', 'PE'),
  ('pe-chiclayo', 'Chiclayo', 'PE'),
  ('pe-piura', 'Piura', 'PE'),
  ('pe-iquitos', 'Iquitos', 'PE'),
  ('pe-cusco', 'Cusco', 'PE'),
  ('pe-chimbote', 'Chimbote', 'PE'),
  ('pe-huancayo', 'Huancayo', 'PE'),
  ('pe-tacna', 'Tacna', 'PE'),
  ('pe-juliaca', 'Juliaca', 'PE'),
  ('pe-ica', 'Ica', 'PE'),
  ('pe-sullana', 'Sullana', 'PE'),
  ('pe-cajamarca', 'Cajamarca', 'PE'),
  ('pe-pucallpa', 'Pucallpa', 'PE'),
  ('pe-ayacucho', 'Ayacucho', 'PE'),

  -- UAE already dense; Saudi extra
  ('sa-jeddah', 'Jeddah', 'SA'),
  ('sa-riyadh', 'Riyadh', 'SA'),
  ('sa-tabuk', 'Tabuk', 'SA'),
  ('sa-buraidah', 'Buraidah', 'SA'),
  ('sa-khamis-mushait', 'Khamis Mushait', 'SA'),
  ('sa-hail', 'Hail', 'SA'),
  ('sa-najran', 'Najran', 'SA'),
  ('sa-al-jubail', 'Al Jubail', 'SA'),
  ('sa-yanbu', 'Yanbu', 'SA'),
  ('sa-abha', 'Abha', 'SA'),
  ('sa-jizan', 'Jizan', 'SA'),
  ('sa-al-kharj', 'Al Kharj', 'SA'),
  ('sa-hafr-al-batin', 'Hafr Al Batin', 'SA'),
  ('sa-taif', 'Taif', 'SA'),
  ('sa-qatif', 'Qatif', 'SA'),

  -- Bangladesh extra
  ('bd-gazipur', 'Gazipur', 'BD'),
  ('bd-narayanganj', 'Narayanganj', 'BD'),
  ('bd-comilla', 'Comilla', 'BD'),
  ('bd-rangpur', 'Rangpur', 'BD'),
  ('bd-barisal', 'Barisal', 'BD'),
  ('bd-mymensingh', 'Mymensingh', 'BD'),
  ('bd-bogura', 'Bogura', 'BD'),
  ('bd-jessore', 'Jessore', 'BD'),
  ('bd-cox-s-bazar', 'Cox''s Bazar', 'BD'),
  ('bd-dinajpur', 'Dinajpur', 'BD'),

  -- Russia major
  ('ru-saint-petersburg', 'Saint Petersburg', 'RU'),
  ('ru-novosibirsk', 'Novosibirsk', 'RU'),
  ('ru-yekaterinburg', 'Yekaterinburg', 'RU'),
  ('ru-kazan', 'Kazan', 'RU'),
  ('ru-nizhny-novgorod', 'Nizhny Novgorod', 'RU'),
  ('ru-chelyabinsk', 'Chelyabinsk', 'RU'),
  ('ru-samara', 'Samara', 'RU'),
  ('ru-omsk', 'Omsk', 'RU'),
  ('ru-rostov-on-don', 'Rostov-on-Don', 'RU'),
  ('ru-ufa', 'Ufa', 'RU'),
  ('ru-krasnoyarsk', 'Krasnoyarsk', 'RU'),
  ('ru-voronezh', 'Voronezh', 'RU'),
  ('ru-perm', 'Perm', 'RU'),
  ('ru-volgograd', 'Volgograd', 'RU'),
  ('ru-krasnodar', 'Krasnodar', 'RU'),

  -- Vietnam
  ('vn-ho-chi-minh', 'Ho Chi Minh City', 'VN'),
  ('vn-hanoi', 'Hanoi', 'VN'),
  ('vn-da-nang', 'Da Nang', 'VN'),
  ('vn-hai-phong', 'Hai Phong', 'VN'),
  ('vn-can-tho', 'Can Tho', 'VN'),
  ('vn-bien-hoa', 'Bien Hoa', 'VN'),
  ('vn-hue', 'Huế', 'VN'),
  ('vn-nha-trang', 'Nha Trang', 'VN'),
  ('vn-buon-ma-thuot', 'Buon Ma Thuot', 'VN'),
  ('vn-vung-tau', 'Vung Tau', 'VN'),
  ('vn-qui-nhon', 'Qui Nhon', 'VN'),
  ('vn-rach-gia', 'Rach Gia', 'VN'),
  ('vn-long-xuyen', 'Long Xuyen', 'VN'),
  ('vn-thai-nguyen', 'Thai Nguyen', 'VN'),
  ('vn-nam-dinh', 'Nam Dinh', 'VN'),

  -- Israel
  ('il-tel-aviv', 'Tel Aviv', 'IL'),
  ('il-haifa', 'Haifa', 'IL'),
  ('il-rishon-lezion', 'Rishon LeZion', 'IL'),
  ('il-petah-tikva', 'Petah Tikva', 'IL'),
  ('il-ashdod', 'Ashdod', 'IL'),
  ('il-netanya', 'Netanya', 'IL'),
  ('il-beer-sheva', 'Beersheba', 'IL'),
  ('il-bnei-brak', 'Bnei Brak', 'IL'),
  ('il-holon', 'Holon', 'IL'),
  ('il-ramat-gan', 'Ramat Gan', 'IL'),
  ('il-rehovot', 'Rehovot', 'IL'),
  ('il-ashkelon', 'Ashkelon', 'IL'),
  ('il-bat-yam', 'Bat Yam', 'IL'),
  ('il-herzliya', 'Herzliya', 'IL'),
  ('il-kfar-saba', 'Kfar Saba', 'IL'),

  -- Greece
  ('gr-thessaloniki', 'Thessaloniki', 'GR'),
  ('gr-patras', 'Patras', 'GR'),
  ('gr-heraklion', 'Heraklion', 'GR'),
  ('gr-larissa', 'Larissa', 'GR'),
  ('gr-volos', 'Volos', 'GR'),
  ('gr-ioannina', 'Ioannina', 'GR'),
  ('gr-chalcis', 'Chalcis', 'GR'),
  ('gr-serres', 'Serres', 'GR'),
  ('gr-alexandroupoli', 'Alexandroupoli', 'GR'),
  ('gr-xanthi', 'Xanthi', 'GR'),
  ('gr-katerini', 'Katerini', 'GR'),
  ('gr-kavala', 'Kavala', 'GR'),
  ('gr-kalamata', 'Kalamata', 'GR'),
  ('gr-rhodes', 'Rhodes', 'GR'),
  ('gr-chania', 'Chania', 'GR'),

  -- Czechia
  ('cz-brno', 'Brno', 'CZ'),
  ('cz-ostrava', 'Ostrava', 'CZ'),
  ('cz-plzen', 'Plzeň', 'CZ'),
  ('cz-liberec', 'Liberec', 'CZ'),
  ('cz-olomouc', 'Olomouc', 'CZ'),
  ('cz-budejovice', 'České Budějovice', 'CZ'),
  ('cz-hradec', 'Hradec Králové', 'CZ'),
  ('cz-ustinadlabem', 'Ústí nad Labem', 'CZ'),
  ('cz-pardubice', 'Pardubice', 'CZ'),
  ('cz-zlin', 'Zlín', 'CZ'),
  ('cz-havirov', 'Havířov', 'CZ'),
  ('cz-kladno', 'Kladno', 'CZ'),
  ('cz-most', 'Most', 'CZ'),
  ('cz-opava', 'Opava', 'CZ'),
  ('cz-frydek', 'Frýdek-Místek', 'CZ'),

  -- Hungary
  ('hu-debrecen', 'Debrecen', 'HU'),
  ('hu-szeged', 'Szeged', 'HU'),
  ('hu-miskolc', 'Miskolc', 'HU'),
  ('hu-pecs', 'Pécs', 'HU'),
  ('hu-gyor', 'Győr', 'HU'),
  ('hu-nyiregyhaza', 'Nyíregyháza', 'HU'),
  ('hu-kecskemet', 'Kecskemét', 'HU'),
  ('hu-szekesfehervar', 'Székesfehérvár', 'HU'),
  ('hu-szombathely', 'Szombathely', 'HU'),
  ('hu-szolnok', 'Szolnok', 'HU'),
  ('hu-tatabanya', 'Tatabánya', 'HU'),
  ('hu-kaposvar', 'Kaposvár', 'HU'),
  ('hu-erd', 'Érd', 'HU'),
  ('hu-veszprem', 'Veszprém', 'HU'),
  ('hu-budaors', 'Budaörs', 'HU'),

  -- Romania
  ('ro-cluj-napoca', 'Cluj-Napoca', 'RO'),
  ('ro-timisoara', 'Timișoara', 'RO'),
  ('ro-iasi', 'Iași', 'RO'),
  ('ro-constanta', 'Constanța', 'RO'),
  ('ro-craiova', 'Craiova', 'RO'),
  ('ro-brasov', 'Brașov', 'RO'),
  ('ro-galati', 'Galați', 'RO'),
  ('ro-ploiesti', 'Ploiești', 'RO'),
  ('ro-oradea', 'Oradea', 'RO'),
  ('ro-braila', 'Brăila', 'RO'),
  ('ro-arad', 'Arad', 'RO'),
  ('ro-pitesti', 'Pitești', 'RO'),
  ('ro-sibiu', 'Sibiu', 'RO'),
  ('ro-bacau', 'Bacău', 'RO'),
  ('ro-targu-mures', 'Târgu Mureș', 'RO'),

  -- Ukraine
  ('ua-kharkiv', 'Kharkiv', 'UA'),
  ('ua-odesa', 'Odesa', 'UA'),
  ('ua-dnipro', 'Dnipro', 'UA'),
  ('ua-donetsk', 'Donetsk', 'UA'),
  ('ua-zaporizhzhia', 'Zaporizhzhia', 'UA'),
  ('ua-lviv', 'Lviv', 'UA'),
  ('ua-kryvyi-rih', 'Kryvyi Rih', 'UA'),
  ('ua-mykolaiv', 'Mykolaiv', 'UA'),
  ('ua-mariupol', 'Mariupol', 'UA'),
  ('ua-luhansk', 'Luhansk', 'UA'),
  ('ua-vinnytsia', 'Vinnytsia', 'UA'),
  ('ua-simferopol', 'Simferopol', 'UA'),
  ('ua-kherson', 'Kherson', 'UA'),
  ('ua-poltava', 'Poltava', 'UA'),
  ('ua-chernihiv', 'Chernihiv', 'UA'),

  -- Kenya
  ('ke-mombasa', 'Mombasa', 'KE'),
  ('ke-kisumu', 'Kisumu', 'KE'),
  ('ke-nakuru', 'Nakuru', 'KE'),
  ('ke-eldoret', 'Eldoret', 'KE'),
  ('ke-thika', 'Thika', 'KE'),
  ('ke-malindi', 'Malindi', 'KE'),
  ('ke-kitale', 'Kitale', 'KE'),
  ('ke-garissa', 'Garissa', 'KE'),
  ('ke-kakamega', 'Kakamega', 'KE'),
  ('ke-nyeri', 'Nyeri', 'KE'),

  -- Morocco
  ('ma-casablanca', 'Casablanca', 'MA'),
  ('ma-fes', 'Fes', 'MA'),
  ('ma-tangier', 'Tangier', 'MA'),
  ('ma-marrakesh', 'Marrakesh', 'MA'),
  ('ma-sale', 'Salé', 'MA'),
  ('ma-meknes', 'Meknes', 'MA'),
  ('ma-rabat', 'Rabat', 'MA'),
  ('ma-oujda', 'Oujda', 'MA'),
  ('ma-kenitra', 'Kenitra', 'MA'),
  ('ma-agadir', 'Agadir', 'MA'),
  ('ma-tetouan', 'Tétouan', 'MA'),
  ('ma-safi', 'Safi', 'MA'),
  ('ma-mohammedia', 'Mohammedia', 'MA'),
  ('ma-el-jadida', 'El Jadida', 'MA'),
  ('ma-nador', 'Nador', 'MA'),

  -- Kuwait / Qatar / Singapore densify slightly
  ('kw-hawalli', 'Hawalli', 'KW'),
  ('kw-salmiya', 'Salmiya', 'KW'),
  ('kw-farwaniya', 'Farwaniya', 'KW'),
  ('kw-jahra', 'Jahra', 'KW'),
  ('kw-ahmadi', 'Ahmadi', 'KW'),
  ('kw-fahaheel', 'Fahaheel', 'KW'),
  ('kw-mangaf', 'Mangaf', 'KW'),
  ('kw-mahboula', 'Mahboula', 'KW'),
  ('qa-al-rayyan', 'Al Rayyan', 'QA'),
  ('qa-al-wakrah', 'Al Wakrah', 'QA'),
  ('qa-umm-salal', 'Umm Salal', 'QA'),
  ('qa-al-khor', 'Al Khor', 'QA'),
  ('qa-dukhan', 'Dukhan', 'QA'),
  ('qa-lusail', 'Lusail', 'QA'),
  ('sg-jurong', 'Jurong', 'SG'),
  ('sg-tampines', 'Tampines', 'SG'),
  ('sg-woodlands', 'Woodlands', 'SG'),
  ('sg-bedok', 'Bedok', 'SG'),
  ('sg-hougang', 'Hougang', 'SG'),
  ('sg-yishun', 'Yishun', 'SG'),
  ('sg-sengkang', 'Sengkang', 'SG'),
  ('sg-ang-mo-kio', 'Ang Mo Kio', 'SG'),
  ('sg-clementi', 'Clementi', 'SG'),
  ('sg-bukit-batok', 'Bukit Batok', 'SG'),

  -- Hong Kong / Taiwan
  ('hk-kowloon', 'Kowloon', 'HK'),
  ('hk-tsuen-wan', 'Tsuen Wan', 'HK'),
  ('hk-sha-tin', 'Sha Tin', 'HK'),
  ('hk-tuen-mun', 'Tuen Mun', 'HK'),
  ('hk-tai-po', 'Tai Po', 'HK'),
  ('hk-yuen-long', 'Yuen Long', 'HK'),
  ('hk-tseung-kwan-o', 'Tseung Kwan O', 'HK'),
  ('hk-sai-kung', 'Sai Kung', 'HK'),
  ('tw-kaohsiung', 'Kaohsiung', 'TW'),
  ('tw-taichung', 'Taichung', 'TW'),
  ('tw-tainan', 'Tainan', 'TW'),
  ('tw-taoyuan', 'Taoyuan', 'TW'),
  ('tw-hsinchu', 'Hsinchu', 'TW'),
  ('tw-keelung', 'Keelung', 'TW'),
  ('tw-chiayi', 'Chiayi', 'TW'),
  ('tw-changhua', 'Changhua', 'TW'),
  ('tw-pingtung', 'Pingtung', 'TW'),
  ('tw-yilan', 'Yilan', 'TW'),

  -- Sri Lanka
  ('lk-kandy', 'Kandy', 'LK'),
  ('lk-galle', 'Galle', 'LK'),
  ('lk-jaffna', 'Jaffna', 'LK'),
  ('lk-negombo', 'Negombo', 'LK'),
  ('lk-trincomalee', 'Trincomalee', 'LK'),
  ('lk-batticaloa', 'Batticaloa', 'LK'),
  ('lk-anuradhapura', 'Anuradhapura', 'LK'),
  ('lk-ratnapura', 'Ratnapura', 'LK'),
  ('lk-matara', 'Matara', 'LK'),
  ('lk-kurunegala', 'Kurunegala', 'LK')
) AS v(id, name, country_code)
WHERE NOT EXISTS (SELECT 1 FROM cities c WHERE c.id = v.id);
