spring:
  application:
    name: scraper-microsoft
  profiles:
    active: dev

server:
  port: 8082

scraper:
  microsoft:
    careers-url: https://careers.microsoft.com/v2/global/en/search.html?q=software+engineer
    timeout-ms: 15000

logging:
  level:
    root: INFO
    com.datascraper: INFO
