spring:
  application:
    name: scraper-google
  profiles:
    active: dev

server:
  port: 8081

scraper:
  google:
    careers-url: https://www.google.com/about/careers/applications/jobs/results?q=software+engineer
    timeout-ms: 15000

logging:
  level:
    root: INFO
    com.datascraper: INFO
