spring:
  application:
    name: scraper-google

server:
  port: 8081

scraper:
  google:
    careers-url: https://www.google.com/about/careers/applications/jobs/results?q=software+engineer
    timeout-ms: 15000
