spring:
  application:
    name: scraper-google
  profiles:
    active: dev

server:
  port: 8081

scraper:
  google:
    timeout-ms: 15000
    urls:
      jobs: https://www.google.com/about/careers/applications/jobs/results?q=software+engineer
      products: https://cloud.google.com/products
      services: https://cloud.google.com/solutions
      company-info: https://about.google/
      contacts: https://about.google/contact-google/
      news: https://blog.google/

logging:
  level:
    root: INFO
    com.datascraper: INFO
