spring:
  application:
    name: scraper-tech
  profiles:
    active: dev

server:
  port: 8092

tech:
  scraper:
    timeout-ms: 15000
    max-items: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
