INSERT INTO categories (id, name) VALUES
  ('software-dev', 'Software Development'),
  ('web-dev', 'Web Development'),
  ('cloud', 'Cloud'),
  ('devops', 'DevOps'),
  ('cyber', 'Cyber Security'),
  ('ai', 'Artificial Intelligence'),
  ('ml', 'Machine Learning'),
  ('data-eng', 'Data Engineering'),
  ('erp', 'ERP'),
  ('crm', 'CRM'),
  ('fintech', 'FinTech'),
  ('healthtech', 'HealthTech'),
  ('edtech', 'EdTech'),
  ('recruitment', 'Recruitment'),
  ('consulting', 'IT Consulting'),
  ('digital-xform', 'Digital Transformation'),
  ('automation', 'Automation'),
  ('blockchain', 'Blockchain'),
  ('mobile', 'Mobile Development'),
  ('saas', 'SaaS'),
  ('api', 'API Development');
