-- Comprehensive worldwide industry category catalog

INSERT INTO categories (id, name)
SELECT v.id, v.name
FROM (VALUES
  ('software', 'Software'),
  ('software-dev', 'Software Development'),
  ('web-dev', 'Web Development'),
  ('mobile-dev', 'Mobile App Development'),
  ('mobile', 'Mobile Development'),
  ('saas', 'SaaS'),
  ('paas', 'Platform as a Service'),
  ('iaas', 'Infrastructure as a Service'),
  ('cloud', 'Cloud Computing'),
  ('devops', 'DevOps'),
  ('sre', 'Site Reliability Engineering'),
  ('cyber', 'Cyber Security'),
  ('cybersecurity', 'Cybersecurity'),
  ('infosec', 'Information Security'),
  ('ai', 'Artificial Intelligence'),
  ('ml', 'Machine Learning'),
  ('deep-learning', 'Deep Learning'),
  ('nlp', 'Natural Language Processing'),
  ('computer-vision', 'Computer Vision'),
  ('data-science', 'Data Science'),
  ('data-eng', 'Data Engineering'),
  ('big-data', 'Big Data'),
  ('analytics', 'Business Analytics'),
  ('bi-software', 'Business Intelligence Software'),
  ('erp', 'ERP'),
  ('crm', 'CRM'),
  ('hris', 'HR Information Systems'),
  ('api', 'API Development'),
  ('blockchain', 'Blockchain'),
  ('cryptocurrency', 'Cryptocurrency'),
  ('web3', 'Web3'),
  ('iot', 'Internet of Things'),
  ('robotics', 'Robotics'),
  ('ar-vr', 'AR / VR'),
  ('gaming', 'Gaming'),
  ('game-dev', 'Game Development'),
  ('it', 'Information Technology'),
  ('it-services', 'IT Services'),
  ('it-support', 'IT Support'),
  ('msp', 'Managed Service Provider'),
  ('outsourcing', 'IT Outsourcing'),
  ('staffing-tech', 'Tech Staffing'),
  ('qa-testing', 'Software Testing & QA'),
  ('ui-ux', 'UI / UX Design'),
  ('product-design', 'Product Design'),
  ('digital-xform', 'Digital Transformation'),
  ('automation', 'Automation'),
  ('rpa', 'Robotic Process Automation'),
  ('low-code', 'Low-Code / No-Code'),
  ('open-source', 'Open Source Software'),
  ('embedded', 'Embedded Systems'),
  ('semiconductor', 'Semiconductors'),
  ('electronics', 'Electronics'),
  ('telecom-software', 'Telecom Software'),
  ('network-security', 'Network Security'),
  ('identity-access', 'Identity & Access Management'),
  ('devops-tools', 'DevOps Tooling'),
  ('observability', 'Observability'),
  ('database', 'Database Software'),
  ('storage-software', 'Storage Software'),
  ('cdn', 'Content Delivery Network'),
  ('hosting', 'Web Hosting'),
  ('domain-registrar', 'Domain Registrar'),
  ('seo-agency', 'SEO Agency'),
  ('digital-marketing', 'Digital Marketing'),
  ('performance-marketing', 'Performance Marketing'),
  ('content-marketing', 'Content Marketing'),
  ('social-media-marketing', 'Social Media Marketing'),
  ('advertising-agency', 'Advertising Agency'),
  ('media-agency', 'Media Agency'),
  ('pr-agency', 'Public Relations'),
  ('branding-agency', 'Branding Agency'),
  ('creative-agency', 'Creative Agency'),
  ('video-production', 'Video Production'),
  ('photography', 'Photography'),
  ('animation', 'Animation Studio'),
  ('streaming', 'Streaming Media'),
  ('podcasting', 'Podcasting'),
  ('publishing', 'Publishing'),
  ('news-media', 'News Media'),
  ('broadcasting', 'Broadcasting'),
  ('finance', 'Finance'),
  ('fintech', 'FinTech'),
  ('banking', 'Banking'),
  ('investment-banking', 'Investment Banking'),
  ('retail-banking', 'Retail Banking'),
  ('commercial-banking', 'Commercial Banking'),
  ('neobank', 'Neobank'),
  ('payments', 'Payments'),
  ('payment-gateway', 'Payment Gateway'),
  ('lending', 'Lending'),
  ('microfinance', 'Microfinance'),
  ('insurance', 'Insurance'),
  ('insurtech', 'InsurTech'),
  ('wealth-management', 'Wealth Management'),
  ('asset-management', 'Asset Management'),
  ('hedge-fund', 'Hedge Fund'),
  ('private-equity', 'Private Equity'),
  ('venture-capital', 'Venture Capital'),
  ('accounting', 'Accounting'),
  ('bookkeeping', 'Bookkeeping'),
  ('tax-services', 'Tax Services'),
  ('audit', 'Audit'),
  ('financial-advisory', 'Financial Advisory'),
  ('credit-union', 'Credit Union'),
  ('forex', 'Foreign Exchange'),
  ('stockbroker', 'Stock Brokerage'),
  ('cryptocurrency-exchange', 'Cryptocurrency Exchange'),
  ('remittance', 'Money Transfer & Remittance'),
  ('healthcare', 'Healthcare'),
  ('healthtech', 'HealthTech'),
  ('hospital', 'Hospitals'),
  ('clinic', 'Medical Clinics'),
  ('dental', 'Dental Clinics'),
  ('dental-lab', 'Dental Laboratories'),
  ('orthodontics', 'Orthodontics'),
  ('ophthalmology', 'Ophthalmology'),
  ('pharmacy', 'Pharmacy'),
  ('pharma', 'Pharmaceuticals'),
  ('biotech', 'Biotechnology'),
  ('medical-devices', 'Medical Devices'),
  ('diagnostics', 'Medical Diagnostics'),
  ('laboratory', 'Medical Laboratories'),
  ('telemedicine', 'Telemedicine'),
  ('mental-health', 'Mental Health Services'),
  ('physiotherapy', 'Physiotherapy'),
  ('chiropractic', 'Chiropractic'),
  ('veterinary', 'Veterinary'),
  ('eldercare', 'Elder Care'),
  ('nursing-home', 'Nursing Homes'),
  ('home-healthcare', 'Home Healthcare'),
  ('ambulance', 'Ambulance Services'),
  ('wellness', 'Wellness'),
  ('fitness', 'Fitness'),
  ('gym', 'Gyms & Fitness Centers'),
  ('yoga-studio', 'Yoga Studios'),
  ('nutrition', 'Nutrition & Dietetics'),
  ('cosmetics-clinic', 'Cosmetic Clinics'),
  ('dermatology', 'Dermatology'),
  ('education', 'Education'),
  ('edtech', 'EdTech'),
  ('schools', 'Schools'),
  ('universities', 'Universities'),
  ('colleges', 'Colleges'),
  ('tutoring', 'Tutoring'),
  ('coaching-centers', 'Coaching Centers'),
  ('language-schools', 'Language Schools'),
  ('vocational-training', 'Vocational Training'),
  ('corporate-training', 'Corporate Training'),
  ('online-learning', 'Online Learning'),
  ('childcare', 'Childcare'),
  ('preschool', 'Preschools'),
  ('library', 'Libraries'),
  ('research-institute', 'Research Institutes'),
  ('construction', 'Construction'),
  ('general-contractor', 'General Contractors'),
  ('civil-engineering', 'Civil Engineering'),
  ('architecture', 'Architecture'),
  ('interior-design', 'Interior Design'),
  ('plumbing', 'Plumbing'),
  ('electrical-contractor', 'Electrical Contractors'),
  ('hvac', 'HVAC'),
  ('roofing', 'Roofing'),
  ('flooring', 'Flooring'),
  ('painting-contractor', 'Painting Contractors'),
  ('landscaping', 'Landscaping'),
  ('excavation', 'Excavation'),
  ('concrete', 'Concrete Services'),
  ('steel-fabrication', 'Steel Fabrication'),
  ('modular-construction', 'Modular Construction'),
  ('real-estate', 'Real Estate'),
  ('real-estate-agency', 'Real Estate Agencies'),
  ('property-management', 'Property Management'),
  ('property-development', 'Property Development'),
  ('commercial-real-estate', 'Commercial Real Estate'),
  ('facility-management', 'Facility Management'),
  ('cleaning', 'Cleaning Companies'),
  ('janitorial', 'Janitorial Services'),
  ('pest-control', 'Pest Control'),
  ('waste-management', 'Waste Management'),
  ('recycling', 'Recycling'),
  ('security-services', 'Security Services'),
  ('private-security', 'Private Security'),
  ('cctv-installation', 'CCTV Installation'),
  ('retail', 'Retail'),
  ('ecommerce', 'E-Commerce'),
  ('marketplace', 'Online Marketplace'),
  ('grocery', 'Grocery Stores'),
  ('supermarket', 'Supermarkets'),
  ('convenience-store', 'Convenience Stores'),
  ('fashion', 'Fashion'),
  ('apparel', 'Apparel'),
  ('footwear', 'Footwear'),
  ('jewelry', 'Jewelry'),
  ('cosmetics', 'Cosmetics'),
  ('beauty-salon', 'Beauty Salons'),
  ('barbershop', 'Barbershops'),
  ('spa', 'Spas'),
  ('nail-salon', 'Nail Salons'),
  ('furniture', 'Furniture'),
  ('home-decor', 'Home Decor'),
  ('electronics-retail', 'Electronics Retail'),
  ('appliance-store', 'Appliance Stores'),
  ('bookstore', 'Bookstores'),
  ('toy-store', 'Toy Stores'),
  ('pet-store', 'Pet Stores'),
  ('pet-services', 'Pet Services'),
  ('florist', 'Florists'),
  ('gift-shop', 'Gift Shops'),
  ('department-store', 'Department Stores'),
  ('luxury-retail', 'Luxury Retail'),
  ('thrift', 'Thrift & Secondhand'),
  ('wholesale', 'Wholesale'),
  ('distribution', 'Distribution'),
  ('import-export', 'Import & Export'),
  ('trading-company', 'Trading Companies'),
  ('food', 'Food & Beverage'),
  ('restaurant', 'Restaurants'),
  ('fast-food', 'Fast Food'),
  ('cafe', 'Cafes'),
  ('coffee-shop', 'Coffee Shops'),
  ('bakery', 'Bakeries'),
  ('catering', 'Catering'),
  ('cloud-kitchen', 'Cloud Kitchens'),
  ('food-delivery', 'Food Delivery'),
  ('beverage', 'Beverage Companies'),
  ('brewery', 'Breweries'),
  ('winery', 'Wineries'),
  ('distillery', 'Distilleries'),
  ('hospitality', 'Hospitality'),
  ('hotel', 'Hotels'),
  ('motel', 'Motels'),
  ('resort', 'Resorts'),
  ('hostel', 'Hostels'),
  ('vacation-rental', 'Vacation Rentals'),
  ('travel-agency', 'Travel Agencies'),
  ('tour-operator', 'Tour Operators'),
  ('airline', 'Airlines'),
  ('airport-services', 'Airport Services'),
  ('cruise', 'Cruise Lines'),
  ('event-management', 'Event Management'),
  ('wedding-services', 'Wedding Services'),
  ('conference-center', 'Conference Centers'),
  ('manufacturing', 'Manufacturing'),
  ('automotive', 'Automotive'),
  ('auto-dealer', 'Auto Dealers'),
  ('auto-repair', 'Auto Repair'),
  ('auto-parts', 'Auto Parts'),
  ('car-rental', 'Car Rental'),
  ('ride-hailing', 'Ride Hailing'),
  ('aerospace', 'Aerospace'),
  ('defense', 'Defense'),
  ('shipbuilding', 'Shipbuilding'),
  ('machinery', 'Machinery'),
  ('industrial-equipment', 'Industrial Equipment'),
  ('tools', 'Tools & Hardware'),
  ('textiles', 'Textiles'),
  ('garment', 'Garment Manufacturing'),
  ('chemicals', 'Chemicals'),
  ('plastics', 'Plastics'),
  ('packaging', 'Packaging'),
  ('paper', 'Paper & Pulp'),
  ('printing', 'Printing'),
  ('metalworking', 'Metalworking'),
  ('mining', 'Mining'),
  ('oil-gas', 'Oil & Gas'),
  ('energy', 'Energy'),
  ('renewable-energy', 'Renewable Energy'),
  ('solar', 'Solar Energy'),
  ('solar-installers', 'Solar Installers'),
  ('wind-energy', 'Wind Energy'),
  ('hydro-energy', 'Hydroelectric Energy'),
  ('nuclear-energy', 'Nuclear Energy'),
  ('utilities', 'Utilities'),
  ('electric-utility', 'Electric Utilities'),
  ('water-utility', 'Water Utilities'),
  ('gas-utility', 'Gas Utilities'),
  ('battery', 'Battery Technology'),
  ('ev-charging', 'EV Charging'),
  ('electric-vehicles', 'Electric Vehicles'),
  ('logistics', 'Logistics'),
  ('freight', 'Freight'),
  ('shipping', 'Shipping'),
  ('trucking', 'Trucking'),
  ('courier', 'Courier Services'),
  ('postal-service', 'Postal Services'),
  ('warehouse', 'Warehousing'),
  ('3pl', 'Third-Party Logistics'),
  ('supply-chain', 'Supply Chain'),
  ('customs-broker', 'Customs Brokerage'),
  ('port-operations', 'Port Operations'),
  ('rail', 'Rail Transport'),
  ('public-transit', 'Public Transit'),
  ('taxi', 'Taxi Services'),
  ('moving-company', 'Moving Companies'),
  ('telecommunications', 'Telecommunications'),
  ('isp', 'Internet Service Providers'),
  ('mobile-carrier', 'Mobile Carriers'),
  ('cable-tv', 'Cable Television'),
  ('satellite', 'Satellite Communications'),
  ('call-center', 'Call Centers'),
  ('bpo', 'Business Process Outsourcing'),
  ('customer-support', 'Customer Support Services'),
  ('consulting', 'Consulting'),
  ('management-consulting', 'Management Consulting'),
  ('strategy-consulting', 'Strategy Consulting'),
  ('it-consulting', 'IT Consulting'),
  ('legal', 'Legal'),
  ('law-firm', 'Law Firms'),
  ('notary', 'Notary Services'),
  ('recruitment', 'Recruitment'),
  ('staffing', 'Staffing Agencies'),
  ('hr-services', 'HR Services'),
  ('payroll', 'Payroll Services'),
  ('translation', 'Translation Services'),
  ('interpreting', 'Interpreting Services'),
  ('market-research', 'Market Research'),
  ('survey', 'Survey Research'),
  ('engineering-services', 'Engineering Services'),
  ('surveying', 'Land Surveying'),
  ('environmental-consulting', 'Environmental Consulting'),
  ('safety-consulting', 'Safety Consulting'),
  ('quality-assurance', 'Quality Assurance Services'),
  ('agriculture', 'Agriculture'),
  ('agtech', 'AgTech'),
  ('farming', 'Farming'),
  ('livestock', 'Livestock'),
  ('fisheries', 'Fisheries'),
  ('aquaculture', 'Aquaculture'),
  ('forestry', 'Forestry'),
  ('horticulture', 'Horticulture'),
  ('fertilizer', 'Fertilizers'),
  ('seeds', 'Seeds & Agri Inputs'),
  ('irrigation', 'Irrigation'),
  ('food-processing', 'Food Processing'),
  ('dairy', 'Dairy'),
  ('meat-processing', 'Meat Processing'),
  ('environmental-services', 'Environmental Services'),
  ('water-treatment', 'Water Treatment'),
  ('air-quality', 'Air Quality Services'),
  ('carbon-credits', 'Carbon Credits'),
  ('climate-tech', 'Climate Tech'),
  ('government', 'Government'),
  ('public-sector', 'Public Sector'),
  ('municipal', 'Municipal Services'),
  ('non-profit', 'Non-Profit'),
  ('ngo', 'NGOs'),
  ('charity', 'Charities'),
  ('foundation', 'Foundations'),
  ('association', 'Associations'),
  ('chamber-of-commerce', 'Chambers of Commerce'),
  ('religious-org', 'Religious Organizations'),
  ('laundry', 'Laundry & Dry Cleaning'),
  ('tailoring', 'Tailoring'),
  ('shoe-repair', 'Shoe Repair'),
  ('locksmith', 'Locksmiths'),
  ('glass-glazing', 'Glass & Glazing'),
  ('signage', 'Signage'),
  ('printing-services', 'Printing Services'),
  ('copier-services', 'Copier & Print Services'),
  ('office-supplies', 'Office Supplies'),
  ('coworking', 'Coworking Spaces'),
  ('business-center', 'Business Centers'),
  ('storage-facility', 'Self Storage'),
  ('funeral-services', 'Funeral Services'),
  ('cemetery', 'Cemeteries'),
  ('pawnshop', 'Pawnshops'),
  ('auction', 'Auction Houses'),
  ('antique', 'Antique Dealers'),
  ('art-gallery', 'Art Galleries'),
  ('museum', 'Museums'),
  ('theater', 'Theaters'),
  ('cinema', 'Cinemas'),
  ('amusement-park', 'Amusement Parks'),
  ('sports-club', 'Sports Clubs'),
  ('sports-equipment', 'Sports Equipment'),
  ('outdoor-recreation', 'Outdoor Recreation'),
  ('tourism', 'Tourism'),
  ('adventure-travel', 'Adventure Travel'),
  ('medical-tourism', 'Medical Tourism'),
  ('immigration-services', 'Immigration Services'),
  ('visa-services', 'Visa Services'),
  ('embassy-services', 'Embassy Support Services'),
  ('language-services', 'Language Services'),
  ('test-prep', 'Test Preparation'),
  ('career-coaching', 'Career Coaching'),
  ('life-coaching', 'Life Coaching'),
  ('personal-training', 'Personal Training'),
  ('martial-arts', 'Martial Arts Schools'),
  ('dance-studio', 'Dance Studios'),
  ('music-school', 'Music Schools'),
  ('art-school', 'Art Schools'),
  ('driving-school', 'Driving Schools'),
  ('boat-services', 'Boat & Marine Services'),
  ('marina', 'Marinas'),
  ('diving', 'Diving Centers'),
  ('ski-resort', 'Ski Resorts'),
  ('camping', 'Camping & Outdoor Gear'),
  ('hunting', 'Hunting & Fishing Outfitters'),
  ('firearm-dealer', 'Firearm Dealers'),
  ('tobacco', 'Tobacco Products'),
  ('cannabis', 'Cannabis'),
  ('vape', 'Vape Retail'),
  ('alcohol-retail', 'Alcohol Retail'),
  ('liquor-store', 'Liquor Stores'),
  ('pharmacy-retail', 'Pharmacy Retail'),
  ('optical', 'Optical Stores'),
  ('hearing-aids', 'Hearing Aids'),
  ('prosthetics', 'Prosthetics'),
  ('mobility-aids', 'Mobility Aids'),
  ('wheelchair', 'Wheelchair Services'),
  ('home-care', 'Home Care Services'),
  ('nanny-agency', 'Nanny Agencies'),
  ('elder-companion', 'Elder Companion Services'),
  ('handyman', 'Handyman Services'),
  ('appliance-repair', 'Appliance Repair'),
  ('phone-repair', 'Phone Repair'),
  ('computer-repair', 'Computer Repair'),
  ('data-recovery', 'Data Recovery'),
  ('it-recycling', 'IT Asset Recycling'),
  ('3d-printing', '3D Printing'),
  ('prototyping', 'Prototyping Services'),
  ('makerspace', 'Makerspaces'),
  ('incubator', 'Business Incubators'),
  ('accelerator', 'Startup Accelerators'),
  ('coworking-tech', 'Tech Coworking'),
  ('shared-kitchen', 'Shared Kitchens'),
  ('dark-store', 'Dark Stores'),
  ('quick-commerce', 'Quick Commerce'),
  ('subscription-box', 'Subscription Boxes'),
  ('direct-to-consumer', 'Direct-to-Consumer Brands'),
  ('private-label', 'Private Label'),
  ('contract-manufacturing', 'Contract Manufacturing'),
  ('oem', 'OEM Manufacturing'),
  ('odm', 'ODM Manufacturing'),
  ('quality-inspection', 'Quality Inspection'),
  ('certification', 'Certification Bodies'),
  ('standards', 'Standards Organizations'),
  ('testing-lab', 'Testing Laboratories'),
  ('calibration', 'Calibration Services'),
  ('metrology', 'Metrology'),
  ('geospatial', 'Geospatial Services'),
  ('gis', 'GIS Services'),
  ('drone-services', 'Drone Services'),
  ('survey-mapping', 'Survey & Mapping'),
  ('weather-services', 'Weather Services'),
  ('space-tech', 'Space Technology'),
  ('satellite-imagery', 'Satellite Imagery'),
  ('defense-tech', 'Defense Technology'),
  ('public-safety', 'Public Safety Tech'),
  ('smart-city', 'Smart City Solutions'),
  ('building-automation', 'Building Automation'),
  ('access-control', 'Access Control Systems'),
  ('fire-safety', 'Fire Safety'),
  ('alarms', 'Alarm Systems'),
  ('smart-home', 'Smart Home'),
  ('home-automation', 'Home Automation'),
  ('proptech', 'PropTech'),
  ('contech', 'Construction Tech'),
  ('legaltech', 'LegalTech'),
  ('regtech', 'RegTech'),
  ('govtech', 'GovTech'),
  ('martech', 'MarTech'),
  ('adtech', 'AdTech'),
  ('hrtech', 'HR Tech'),
  ('edtech-tools', 'Education Technology Tools'),
  ('health-it', 'Health IT'),
  ('emr', 'Electronic Medical Records'),
  ('telehealth-platform', 'Telehealth Platforms'),
  ('pharmacy-tech', 'Pharmacy Technology'),
  ('medtech', 'MedTech'),
  ('cleantech', 'CleanTech'),
  ('greentech', 'GreenTech'),
  ('watertech', 'WaterTech'),
  ('foodtech', 'FoodTech'),
  ('retailtech', 'RetailTech'),
  ('logistics-tech', 'Logistics Tech'),
  ('mobility-tech', 'Mobility Tech'),
  ('autonomous-vehicles', 'Autonomous Vehicles'),
  ('micromobility', 'Micromobility'),
  ('bike-sharing', 'Bike Sharing'),
  ('scooter-sharing', 'Scooter Sharing'),
  ('parking', 'Parking Services'),
  ('tolling', 'Tolling Systems'),
  ('fleet-management', 'Fleet Management'),
  ('telematics', 'Telematics'),
  ('insurance-broker', 'Insurance Brokers'),
  ('claims-management', 'Claims Management'),
  ('actuarial', 'Actuarial Services'),
  ('risk-management', 'Risk Management'),
  ('compliance', 'Compliance Services'),
  ('kyc-aml', 'KYC / AML Services'),
  ('fraud-prevention', 'Fraud Prevention'),
  ('credit-bureau', 'Credit Bureaus'),
  ('collections', 'Debt Collections'),
  ('factoring', 'Factoring'),
  ('leasing', 'Equipment Leasing'),
  ('pawn-lending', 'Pawn Lending'),
  ('crowdfunding', 'Crowdfunding'),
  ('p2p-lending', 'Peer-to-Peer Lending'),
  ('islamic-finance', 'Islamic Finance'),
  ('micro-insurance', 'Microinsurance'),
  ('reinsurance', 'Reinsurance')
) AS v(id, name)
WHERE NOT EXISTS (SELECT 1 FROM categories c WHERE c.id = v.id);

