-- Add IT, AI, and software industry categories alongside existing local-business catalog.

INSERT INTO categories (id, name)
SELECT v.id, v.name
FROM (VALUES
  ('software', 'Software'),
  ('software-dev', 'Software Development'),
  ('web-dev', 'Web Development'),
  ('mobile-dev', 'Mobile App Development'),
  ('saas', 'SaaS'),
  ('cloud', 'Cloud Computing'),
  ('devops', 'DevOps'),
  ('cybersecurity', 'Cybersecurity'),
  ('infosec', 'Information Security'),
  ('ai', 'Artificial Intelligence'),
  ('ml', 'Machine Learning'),
  ('deep-learning', 'Deep Learning'),
  ('nlp', 'Natural Language Processing'),
  ('computer-vision', 'Computer Vision'),
  ('data-science', 'Data Science'),
  ('data-eng', 'Data Engineering'),
  ('bi-software', 'Business Intelligence Software'),
  ('it', 'Information Technology'),
  ('it-services', 'IT Services'),
  ('it-support', 'IT Support'),
  ('it-consulting', 'IT Consulting'),
  ('msp', 'Managed Service Provider'),
  ('outsourcing', 'IT Outsourcing'),
  ('qa-testing', 'Software Testing & QA'),
  ('ui-ux', 'UI / UX Design'),
  ('automation', 'Automation'),
  ('rpa', 'Robotic Process Automation'),
  ('blockchain', 'Blockchain'),
  ('web3', 'Web3'),
  ('iot', 'Internet of Things'),
  ('robotics', 'Robotics'),
  ('game-dev', 'Game Development'),
  ('hosting', 'Web Hosting'),
  ('open-source', 'Open Source Software'),
  ('digital-xform', 'Digital Transformation'),
  ('fintech', 'FinTech'),
  ('healthtech', 'HealthTech'),
  ('edtech', 'EdTech'),
  ('martech', 'MarTech'),
  ('api', 'API Development'),
  ('low-code', 'Low-Code / No-Code'),
  ('observability', 'Observability'),
  ('database', 'Database Software'),
  ('network-security', 'Network Security'),
  ('identity-access', 'Identity & Access Management')
) AS v(id, name)
WHERE NOT EXISTS (SELECT 1 FROM categories c WHERE c.id = v.id);
