spring:
  application:
    name: scraper-github
  profiles:
    active: dev

server:
  port: 8094

github:
  scraper:
    timeout-ms: 10000
    max-results: 5
    api-base-url: https://api.github.com
    token: ${GITHUB_TOKEN:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
